INSERT INTO `Model` VALUES ('Acura', 'CL');
INSERT INTO `Model` VALUES ('Acura', 'CSX');
INSERT INTO `Model` VALUES ('Acura', 'EL');
INSERT INTO `Model` VALUES ('Acura', 'ILX');
INSERT INTO `Model` VALUES ('Acura', 'Integra');
INSERT INTO `Model` VALUES ('Acura', 'Legend');
INSERT INTO `Model` VALUES ('Acura', 'MDX');
INSERT INTO `Model` VALUES ('Acura', 'NSX');
INSERT INTO `Model` VALUES ('Acura', 'RDX');
INSERT INTO `Model` VALUES ('Acura', 'RL');
INSERT INTO `Model` VALUES ('Acura', 'RLX');
INSERT INTO `Model` VALUES ('Acura', 'RSX');
INSERT INTO `Model` VALUES ('Acura', 'SLX');
INSERT INTO `Model` VALUES ('Acura', 'TL');
INSERT INTO `Model` VALUES ('Acura', 'TLX');
INSERT INTO `Model` VALUES ('Acura', 'TSX');
INSERT INTO `Model` VALUES ('Acura', 'ZDX');
INSERT INTO `Model` VALUES ('Audi', '100');
INSERT INTO `Model` VALUES ('Audi', '200');
INSERT INTO `Model` VALUES ('Audi', '50');
INSERT INTO `Model` VALUES ('Audi', '80');
INSERT INTO `Model` VALUES ('Audi', '90');
INSERT INTO `Model` VALUES ('Audi', '920');
INSERT INTO `Model` VALUES ('Audi', 'A1');
INSERT INTO `Model` VALUES ('Audi', 'A2');
INSERT INTO `Model` VALUES ('Audi', 'A3');
INSERT INTO `Model` VALUES ('Audi', 'A4');
INSERT INTO `Model` VALUES ('Audi', 'A4 allroad');
INSERT INTO `Model` VALUES ('Audi', 'A5');
INSERT INTO `Model` VALUES ('Audi', 'A6');
INSERT INTO `Model` VALUES ('Audi', 'A6 allroad');
INSERT INTO `Model` VALUES ('Audi', 'A7');
INSERT INTO `Model` VALUES ('Audi', 'A8');
INSERT INTO `Model` VALUES ('Audi', 'Cabriolet');
INSERT INTO `Model` VALUES ('Audi', 'Coupe');
INSERT INTO `Model` VALUES ('Audi', 'e-tron');
INSERT INTO `Model` VALUES ('Audi', 'e-tron GT');
INSERT INTO `Model` VALUES ('Audi', 'e-tron S');
INSERT INTO `Model` VALUES ('Audi', 'e-tron S Sportback');
INSERT INTO `Model` VALUES ('Audi', 'e-tron Sportback');
INSERT INTO `Model` VALUES ('Audi', 'NSU RO 80');
INSERT INTO `Model` VALUES ('Audi', 'Q2');
INSERT INTO `Model` VALUES ('Audi', 'Q2L');
INSERT INTO `Model` VALUES ('Audi', 'Q3');
INSERT INTO `Model` VALUES ('Audi', 'Q3 Sportback');
INSERT INTO `Model` VALUES ('Audi', 'Q4 e-tron');
INSERT INTO `Model` VALUES ('Audi', 'Q4 Sportback e-tron');
INSERT INTO `Model` VALUES ('Audi', 'Q5');
INSERT INTO `Model` VALUES ('Audi', 'Q5 e-tron');
INSERT INTO `Model` VALUES ('Audi', 'Q5 Sportback');
INSERT INTO `Model` VALUES ('Audi', 'Q7');
INSERT INTO `Model` VALUES ('Audi', 'Q8');
INSERT INTO `Model` VALUES ('Audi', 'Quattro');
INSERT INTO `Model` VALUES ('Audi', 'R8');
INSERT INTO `Model` VALUES ('Audi', 'R8 LMP');
INSERT INTO `Model` VALUES ('Audi', 'RS 2');
INSERT INTO `Model` VALUES ('Audi', 'RS 3');
INSERT INTO `Model` VALUES ('Audi', 'RS 4');
INSERT INTO `Model` VALUES ('Audi', 'RS 5');
INSERT INTO `Model` VALUES ('Audi', 'RS 6');
INSERT INTO `Model` VALUES ('Audi', 'RS 7');
INSERT INTO `Model` VALUES ('Audi', 'RS e-tron GT');
INSERT INTO `Model` VALUES ('Audi', 'RS Q3');
INSERT INTO `Model` VALUES ('Audi', 'RS Q3 Sportback');
INSERT INTO `Model` VALUES ('Audi', 'RS Q8');
INSERT INTO `Model` VALUES ('Audi', 'S1');
INSERT INTO `Model` VALUES ('Audi', 'S2');
INSERT INTO `Model` VALUES ('Audi', 'S3');
INSERT INTO `Model` VALUES ('Audi', 'S4');
INSERT INTO `Model` VALUES ('Audi', 'S5');
INSERT INTO `Model` VALUES ('Audi', 'S6');
INSERT INTO `Model` VALUES ('Audi', 'S7');
INSERT INTO `Model` VALUES ('Audi', 'S8');
INSERT INTO `Model` VALUES ('Audi', 'SQ2');
INSERT INTO `Model` VALUES ('Audi', 'SQ5');
INSERT INTO `Model` VALUES ('Audi', 'SQ5 Sportback');
INSERT INTO `Model` VALUES ('Audi', 'SQ7');
INSERT INTO `Model` VALUES ('Audi', 'SQ8');
INSERT INTO `Model` VALUES ('Audi', 'TT');
INSERT INTO `Model` VALUES ('Audi', 'TT RS');
INSERT INTO `Model` VALUES ('Audi', 'TTS');
INSERT INTO `Model` VALUES ('Audi', 'Typ R');
INSERT INTO `Model` VALUES ('Audi', 'V8');
INSERT INTO `Model` VALUES ('BMW', '02 (E10)');
INSERT INTO `Model` VALUES ('BMW', '1 серии');
INSERT INTO `Model` VALUES ('BMW', '1M');
INSERT INTO `Model` VALUES ('BMW', '2 серии');
INSERT INTO `Model` VALUES ('BMW', '2 серии Active Tourer');
INSERT INTO `Model` VALUES ('BMW', '2 серии Gran Tourer');
INSERT INTO `Model` VALUES ('BMW', '2000 C/CS');
INSERT INTO `Model` VALUES ('BMW', '3 серии');
INSERT INTO `Model` VALUES ('BMW', '3/15');
INSERT INTO `Model` VALUES ('BMW', '315');
INSERT INTO `Model` VALUES ('BMW', '3200');
INSERT INTO `Model` VALUES ('BMW', '321');
INSERT INTO `Model` VALUES ('BMW', '326');
INSERT INTO `Model` VALUES ('BMW', '327');
INSERT INTO `Model` VALUES ('BMW', '340');
INSERT INTO `Model` VALUES ('BMW', '4 серии');
INSERT INTO `Model` VALUES ('BMW', '5 серии');
INSERT INTO `Model` VALUES ('BMW', '501');
INSERT INTO `Model` VALUES ('BMW', '502');
INSERT INTO `Model` VALUES ('BMW', '503');
INSERT INTO `Model` VALUES ('BMW', '507');
INSERT INTO `Model` VALUES ('BMW', '6 серии');
INSERT INTO `Model` VALUES ('BMW', '600');
INSERT INTO `Model` VALUES ('BMW', '7 серии');
INSERT INTO `Model` VALUES ('BMW', '700');
INSERT INTO `Model` VALUES ('BMW', '8 серии');
INSERT INTO `Model` VALUES ('BMW', 'E3');
INSERT INTO `Model` VALUES ('BMW', 'E9');
INSERT INTO `Model` VALUES ('BMW', 'i3');
INSERT INTO `Model` VALUES ('BMW', 'i4');
INSERT INTO `Model` VALUES ('BMW', 'i7');
INSERT INTO `Model` VALUES ('BMW', 'i8');
INSERT INTO `Model` VALUES ('BMW', 'iX');
INSERT INTO `Model` VALUES ('BMW', 'iX1');
INSERT INTO `Model` VALUES ('BMW', 'iX3');
INSERT INTO `Model` VALUES ('BMW', 'M2');
INSERT INTO `Model` VALUES ('BMW', 'M3');
INSERT INTO `Model` VALUES ('BMW', 'M4');
INSERT INTO `Model` VALUES ('BMW', 'M5');
INSERT INTO `Model` VALUES ('BMW', 'M6');
INSERT INTO `Model` VALUES ('BMW', 'M8');
INSERT INTO `Model` VALUES ('BMW', 'New Class');
INSERT INTO `Model` VALUES ('BMW', 'X1');
INSERT INTO `Model` VALUES ('BMW', 'X2');
INSERT INTO `Model` VALUES ('BMW', 'X3');
INSERT INTO `Model` VALUES ('BMW', 'X3 M');
INSERT INTO `Model` VALUES ('BMW', 'X4');
INSERT INTO `Model` VALUES ('BMW', 'X4 M');
INSERT INTO `Model` VALUES ('BMW', 'X5');
INSERT INTO `Model` VALUES ('BMW', 'X5 M');
INSERT INTO `Model` VALUES ('BMW', 'X6');
INSERT INTO `Model` VALUES ('BMW', 'X6 M');
INSERT INTO `Model` VALUES ('BMW', 'X7');
INSERT INTO `Model` VALUES ('BMW', 'XM');
INSERT INTO `Model` VALUES ('BMW', 'Z1');
INSERT INTO `Model` VALUES ('BMW', 'Z3');
INSERT INTO `Model` VALUES ('BMW', 'Z3 M');
INSERT INTO `Model` VALUES ('BMW', 'Z4');
INSERT INTO `Model` VALUES ('BMW', 'Z4 M');
INSERT INTO `Model` VALUES ('BMW', 'Z8');
INSERT INTO `Model` VALUES ('Brilliance', 'FRV (BS2)');
INSERT INTO `Model` VALUES ('Brilliance', 'H230');
INSERT INTO `Model` VALUES ('Brilliance', 'H530');
INSERT INTO `Model` VALUES ('Brilliance', 'M1 (BS6)');
INSERT INTO `Model` VALUES ('Brilliance', 'M2 (BS4)');
INSERT INTO `Model` VALUES ('Brilliance', 'M3 (BC3)');
INSERT INTO `Model` VALUES ('Brilliance', 'V3');
INSERT INTO `Model` VALUES ('Brilliance', 'V5');
INSERT INTO `Model` VALUES ('Chery', 'Amulet (A15)');
INSERT INTO `Model` VALUES ('Chery', 'Arrizo 3');
INSERT INTO `Model` VALUES ('Chery', 'Arrizo 6');
INSERT INTO `Model` VALUES ('Chery', 'Arrizo 7');
INSERT INTO `Model` VALUES ('Chery', 'B13');
INSERT INTO `Model` VALUES ('Chery', 'Bonus (A13)');
INSERT INTO `Model` VALUES ('Chery', 'Bonus 3 (E3/A19)');
INSERT INTO `Model` VALUES ('Chery', 'CrossEastar (B14)');
INSERT INTO `Model` VALUES ('Chery', 'E5');
INSERT INTO `Model` VALUES ('Chery', 'eQ5');
INSERT INTO `Model` VALUES ('Chery', 'Fora (A21)');
INSERT INTO `Model` VALUES ('Chery', 'IndiS (S18D)');
INSERT INTO `Model` VALUES ('Chery', 'Karry');
INSERT INTO `Model` VALUES ('Chery', 'Kimo (A1)');
INSERT INTO `Model` VALUES ('Chery', 'M11 (A3)');
INSERT INTO `Model` VALUES ('Chery', 'Oriental Son (B11)');
INSERT INTO `Model` VALUES ('Chery', 'QQ6 (S21)');
INSERT INTO `Model` VALUES ('Chery', 'QQme');
INSERT INTO `Model` VALUES ('Chery', 'Sweet (QQ)');
INSERT INTO `Model` VALUES ('Chery', 'Tiggo (T11)');
INSERT INTO `Model` VALUES ('Chery', 'Tiggo 2');
INSERT INTO `Model` VALUES ('Chery', 'Tiggo 2 Pro');
INSERT INTO `Model` VALUES ('Chery', 'Tiggo 3');
INSERT INTO `Model` VALUES ('Chery', 'Tiggo 3xe');
INSERT INTO `Model` VALUES ('Chery', 'Tiggo 4');
INSERT INTO `Model` VALUES ('Chery', 'Tiggo 4 Pro');
INSERT INTO `Model` VALUES ('Chery', 'Tiggo 5');
INSERT INTO `Model` VALUES ('Chery', 'Tiggo 7');
INSERT INTO `Model` VALUES ('Chery', 'Tiggo 7 Pro');
INSERT INTO `Model` VALUES ('Chery', 'Tiggo 8');
INSERT INTO `Model` VALUES ('Chery', 'Tiggo 8 Pro');
INSERT INTO `Model` VALUES ('Chery', 'Tiggo 8 Pro Max');
INSERT INTO `Model` VALUES ('Chery', 'Very (A13)');
INSERT INTO `Model` VALUES ('Chery', 'Windcloud (A11)');
INSERT INTO `Model` VALUES ('Chevrolet', '3000-Series');
INSERT INTO `Model` VALUES ('Chevrolet', 'Alero');
INSERT INTO `Model` VALUES ('Chevrolet', 'Apache');
INSERT INTO `Model` VALUES ('Chevrolet', 'Astra');
INSERT INTO `Model` VALUES ('Chevrolet', 'Astro');
INSERT INTO `Model` VALUES ('Chevrolet', 'Avalanche');
INSERT INTO `Model` VALUES ('Chevrolet', 'Aveo');
INSERT INTO `Model` VALUES ('Chevrolet', 'Bel Air');
INSERT INTO `Model` VALUES ('Chevrolet', 'Beretta');
INSERT INTO `Model` VALUES ('Chevrolet', 'Blazer');
INSERT INTO `Model` VALUES ('Chevrolet', 'Blazer K5');
INSERT INTO `Model` VALUES ('Chevrolet', 'Bolt');
INSERT INTO `Model` VALUES ('Chevrolet', 'Bolt EUV');
INSERT INTO `Model` VALUES ('Chevrolet', 'C-10');
INSERT INTO `Model` VALUES ('Chevrolet', 'C/K');
INSERT INTO `Model` VALUES ('Chevrolet', 'Camaro');
INSERT INTO `Model` VALUES ('Chevrolet', 'Caprice');
INSERT INTO `Model` VALUES ('Chevrolet', 'Captiva');
INSERT INTO `Model` VALUES ('Chevrolet', 'Captiva Sport');
INSERT INTO `Model` VALUES ('Chevrolet', 'Cavalier');
INSERT INTO `Model` VALUES ('Chevrolet', 'Celebrity');
INSERT INTO `Model` VALUES ('Chevrolet', 'Celta');
INSERT INTO `Model` VALUES ('Chevrolet', 'Chevelle');
INSERT INTO `Model` VALUES ('Chevrolet', 'Chevette');
INSERT INTO `Model` VALUES ('Chevrolet', 'Citation');
INSERT INTO `Model` VALUES ('Chevrolet', 'Cobalt');
INSERT INTO `Model` VALUES ('Chevrolet', 'Colorado');
INSERT INTO `Model` VALUES ('Chevrolet', 'Corsa');
INSERT INTO `Model` VALUES ('Chevrolet', 'Corsica');
INSERT INTO `Model` VALUES ('Chevrolet', 'Corvair');
INSERT INTO `Model` VALUES ('Chevrolet', 'Corvette');
INSERT INTO `Model` VALUES ('Chevrolet', 'Cruze');
INSERT INTO `Model` VALUES ('Chevrolet', 'Cruze (HR)');
INSERT INTO `Model` VALUES ('Chevrolet', 'CSV CR8');
INSERT INTO `Model` VALUES ('Chevrolet', 'Damas');
INSERT INTO `Model` VALUES ('Chevrolet', 'Deluxe');
INSERT INTO `Model` VALUES ('Chevrolet', 'El Camino');
INSERT INTO `Model` VALUES ('Chevrolet', 'Epica');
INSERT INTO `Model` VALUES ('Chevrolet', 'Equinox');
INSERT INTO `Model` VALUES ('Chevrolet', 'Evanda');
INSERT INTO `Model` VALUES ('Chevrolet', 'Express');
INSERT INTO `Model` VALUES ('Chevrolet', 'Fleetmaster');
INSERT INTO `Model` VALUES ('Chevrolet', 'HHR');
INSERT INTO `Model` VALUES ('Chevrolet', 'Impala');
INSERT INTO `Model` VALUES ('Chevrolet', 'Kalos');
INSERT INTO `Model` VALUES ('Chevrolet', 'Lacetti');
INSERT INTO `Model` VALUES ('Chevrolet', 'Lanos');
INSERT INTO `Model` VALUES ('Chevrolet', 'Lumina');
INSERT INTO `Model` VALUES ('Chevrolet', 'Lumina APV');
INSERT INTO `Model` VALUES ('Chevrolet', 'LUV D-MAX');
INSERT INTO `Model` VALUES ('Chevrolet', 'Malibu');
INSERT INTO `Model` VALUES ('Chevrolet', 'Master');
INSERT INTO `Model` VALUES ('Chevrolet', 'Matiz');
INSERT INTO `Model` VALUES ('Chevrolet', 'Menlo');
INSERT INTO `Model` VALUES ('Chevrolet', 'Metro');
INSERT INTO `Model` VALUES ('Chevrolet', 'Monte Carlo');
INSERT INTO `Model` VALUES ('Chevrolet', 'Monza');
INSERT INTO `Model` VALUES ('Chevrolet', 'MW');
INSERT INTO `Model` VALUES ('Chevrolet', 'Nexia');
INSERT INTO `Model` VALUES ('Chevrolet', 'Niva');
INSERT INTO `Model` VALUES ('Chevrolet', 'Nova');
INSERT INTO `Model` VALUES ('Chevrolet', 'Nubira');
INSERT INTO `Model` VALUES ('Chevrolet', 'Omega');
INSERT INTO `Model` VALUES ('Chevrolet', 'Orlando');
INSERT INTO `Model` VALUES ('Chevrolet', 'Prizm');
INSERT INTO `Model` VALUES ('Chevrolet', 'Rezzo');
INSERT INTO `Model` VALUES ('Chevrolet', 'S-10 Pickup');
INSERT INTO `Model` VALUES ('Chevrolet', 'Sail');
INSERT INTO `Model` VALUES ('Chevrolet', 'Silverado');
INSERT INTO `Model` VALUES ('Chevrolet', 'Sonic');
INSERT INTO `Model` VALUES ('Chevrolet', 'Spark');
INSERT INTO `Model` VALUES ('Chevrolet', 'Special DeLuxe');
INSERT INTO `Model` VALUES ('Chevrolet', 'Spin');
INSERT INTO `Model` VALUES ('Chevrolet', 'SS');
INSERT INTO `Model` VALUES ('Chevrolet', 'SSR');
INSERT INTO `Model` VALUES ('Chevrolet', 'Starcraft');
INSERT INTO `Model` VALUES ('Chevrolet', 'Suburban');
INSERT INTO `Model` VALUES ('Chevrolet', 'Tacuma');
INSERT INTO `Model` VALUES ('Chevrolet', 'Tahoe');
INSERT INTO `Model` VALUES ('Chevrolet', 'Tavera');
INSERT INTO `Model` VALUES ('Chevrolet', 'Tracker');
INSERT INTO `Model` VALUES ('Chevrolet', 'TrailBlazer');
INSERT INTO `Model` VALUES ('Chevrolet', 'Trans Sport');
INSERT INTO `Model` VALUES ('Chevrolet', 'Traverse');
INSERT INTO `Model` VALUES ('Chevrolet', 'Trax');
INSERT INTO `Model` VALUES ('Chevrolet', 'Uplander');
INSERT INTO `Model` VALUES ('Chevrolet', 'Van');
INSERT INTO `Model` VALUES ('Chevrolet', 'Vectra');
INSERT INTO `Model` VALUES ('Chevrolet', 'Venture');
INSERT INTO `Model` VALUES ('Chevrolet', 'Viva');
INSERT INTO `Model` VALUES ('Chevrolet', 'Volt');
INSERT INTO `Model` VALUES ('Chevrolet', 'Zafira');
INSERT INTO `Model` VALUES ('Citroen', '2 CV');
INSERT INTO `Model` VALUES ('Citroen', 'AMI');
INSERT INTO `Model` VALUES ('Citroen', 'AX');
INSERT INTO `Model` VALUES ('Citroen', 'Berlingo');
INSERT INTO `Model` VALUES ('Citroen', 'BX');
INSERT INTO `Model` VALUES ('Citroen', 'C-Crosser');
INSERT INTO `Model` VALUES ('Citroen', 'C-Elysee');
INSERT INTO `Model` VALUES ('Citroen', 'C-Quatre');
INSERT INTO `Model` VALUES ('Citroen', 'C-Triomphe');
INSERT INTO `Model` VALUES ('Citroen', 'C-ZERO');
INSERT INTO `Model` VALUES ('Citroen', 'C1');
INSERT INTO `Model` VALUES ('Citroen', 'C2');
INSERT INTO `Model` VALUES ('Citroen', 'C3');
INSERT INTO `Model` VALUES ('Citroen', 'C3 Aircross');
INSERT INTO `Model` VALUES ('Citroen', 'C3 Picasso');
INSERT INTO `Model` VALUES ('Citroen', 'C4');
INSERT INTO `Model` VALUES ('Citroen', 'C4 Aircross');
INSERT INTO `Model` VALUES ('Citroen', 'C4 Cactus');
INSERT INTO `Model` VALUES ('Citroen', 'C4 Picasso');
INSERT INTO `Model` VALUES ('Citroen', 'C4 SpaceTourer');
INSERT INTO `Model` VALUES ('Citroen', 'C5');
INSERT INTO `Model` VALUES ('Citroen', 'C5 Aircross');
INSERT INTO `Model` VALUES ('Citroen', 'C5 X');
INSERT INTO `Model` VALUES ('Citroen', 'C6');
INSERT INTO `Model` VALUES ('Citroen', 'C8');
INSERT INTO `Model` VALUES ('Citroen', 'CX');
INSERT INTO `Model` VALUES ('Citroen', 'DS');
INSERT INTO `Model` VALUES ('Citroen', 'DS3');
INSERT INTO `Model` VALUES ('Citroen', 'DS4');
INSERT INTO `Model` VALUES ('Citroen', 'DS5');
INSERT INTO `Model` VALUES ('Citroen', 'Dyane');
INSERT INTO `Model` VALUES ('Citroen', 'E-Mehari');
INSERT INTO `Model` VALUES ('Citroen', 'Evasion');
INSERT INTO `Model` VALUES ('Citroen', 'GS');
INSERT INTO `Model` VALUES ('Citroen', 'Jumpy');
INSERT INTO `Model` VALUES ('Citroen', 'LN');
INSERT INTO `Model` VALUES ('Citroen', 'Nemo');
INSERT INTO `Model` VALUES ('Citroen', 'Saxo');
INSERT INTO `Model` VALUES ('Citroen', 'SM');
INSERT INTO `Model` VALUES ('Citroen', 'SpaceTourer');
INSERT INTO `Model` VALUES ('Citroen', 'Traction Avant');
INSERT INTO `Model` VALUES ('Citroen', 'Visa');
INSERT INTO `Model` VALUES ('Citroen', 'Xantia');
INSERT INTO `Model` VALUES ('Citroen', 'XM');
INSERT INTO `Model` VALUES ('Citroen', 'Xsara');
INSERT INTO `Model` VALUES ('Citroen', 'Xsara Picasso');
INSERT INTO `Model` VALUES ('Citroen', 'ZX');
INSERT INTO `Model` VALUES ('Daewoo', 'Alpheon');
INSERT INTO `Model` VALUES ('Daewoo', 'Arcadia');
INSERT INTO `Model` VALUES ('Daewoo', 'Chairman');
INSERT INTO `Model` VALUES ('Daewoo', 'Damas');
INSERT INTO `Model` VALUES ('Daewoo', 'Espero');
INSERT INTO `Model` VALUES ('Daewoo', 'Evanda');
INSERT INTO `Model` VALUES ('Daewoo', 'G2X');
INSERT INTO `Model` VALUES ('Daewoo', 'Gentra');
INSERT INTO `Model` VALUES ('Daewoo', 'Kalos');
INSERT INTO `Model` VALUES ('Daewoo', 'Korando');
INSERT INTO `Model` VALUES ('Daewoo', 'Lacetti');
INSERT INTO `Model` VALUES ('Daewoo', 'Lacetti Premiere');
INSERT INTO `Model` VALUES ('Daewoo', 'Lanos');
INSERT INTO `Model` VALUES ('Daewoo', 'Leganza');
INSERT INTO `Model` VALUES ('Daewoo', 'LeMans');
INSERT INTO `Model` VALUES ('Daewoo', 'Magnus');
INSERT INTO `Model` VALUES ('Daewoo', 'Matiz');
INSERT INTO `Model` VALUES ('Daewoo', 'Matiz Creative');
INSERT INTO `Model` VALUES ('Daewoo', 'Musso');
INSERT INTO `Model` VALUES ('Daewoo', 'Nexia');
INSERT INTO `Model` VALUES ('Daewoo', 'Nubira');
INSERT INTO `Model` VALUES ('Daewoo', 'Prince');
INSERT INTO `Model` VALUES ('Daewoo', 'Racer');
INSERT INTO `Model` VALUES ('Daewoo', 'Rezzo');
INSERT INTO `Model` VALUES ('Daewoo', 'Royale');
INSERT INTO `Model` VALUES ('Daewoo', 'Sens');
INSERT INTO `Model` VALUES ('Daewoo', 'Tacuma');
INSERT INTO `Model` VALUES ('Daewoo', 'Tico');
INSERT INTO `Model` VALUES ('Daewoo', 'Tosca');
INSERT INTO `Model` VALUES ('Daewoo', 'Winstorm');
INSERT INTO `Model` VALUES ('Datsun', '240Z');
INSERT INTO `Model` VALUES ('Datsun', '280Z');
INSERT INTO `Model` VALUES ('Datsun', '280ZX');
INSERT INTO `Model` VALUES ('Datsun', '720');
INSERT INTO `Model` VALUES ('Datsun', 'Bluebird');
INSERT INTO `Model` VALUES ('Datsun', 'Cherry');
INSERT INTO `Model` VALUES ('Datsun', 'GO');
INSERT INTO `Model` VALUES ('Datsun', 'GO+');
INSERT INTO `Model` VALUES ('Datsun', 'Laurel');
INSERT INTO `Model` VALUES ('Datsun', 'mi-DO');
INSERT INTO `Model` VALUES ('Datsun', 'on-DO');
INSERT INTO `Model` VALUES ('Datsun', 'Stanza');
INSERT INTO `Model` VALUES ('Datsun', 'Sunny');
INSERT INTO `Model` VALUES ('Datsun', 'Urvan');
INSERT INTO `Model` VALUES ('Datsun', 'Violet');
INSERT INTO `Model` VALUES ('Fiat', '124');
INSERT INTO `Model` VALUES ('Fiat', '124 Spider');
INSERT INTO `Model` VALUES ('Fiat', '124 Sport Spider');
INSERT INTO `Model` VALUES ('Fiat', '125');
INSERT INTO `Model` VALUES ('Fiat', '126');
INSERT INTO `Model` VALUES ('Fiat', '127');
INSERT INTO `Model` VALUES ('Fiat', '128');
INSERT INTO `Model` VALUES ('Fiat', '130');
INSERT INTO `Model` VALUES ('Fiat', '131');
INSERT INTO `Model` VALUES ('Fiat', '132');
INSERT INTO `Model` VALUES ('Fiat', '2300');
INSERT INTO `Model` VALUES ('Fiat', '238');
INSERT INTO `Model` VALUES ('Fiat', '500');
INSERT INTO `Model` VALUES ('Fiat', '500L');
INSERT INTO `Model` VALUES ('Fiat', '500X');
INSERT INTO `Model` VALUES ('Fiat', '508');
INSERT INTO `Model` VALUES ('Fiat', '600');
INSERT INTO `Model` VALUES ('Fiat', '900T');
INSERT INTO `Model` VALUES ('Fiat', 'Albea');
INSERT INTO `Model` VALUES ('Fiat', 'Argenta');
INSERT INTO `Model` VALUES ('Fiat', 'Barchetta');
INSERT INTO `Model` VALUES ('Fiat', 'Brava');
INSERT INTO `Model` VALUES ('Fiat', 'Bravo');
INSERT INTO `Model` VALUES ('Fiat', 'Cinquecento');
INSERT INTO `Model` VALUES ('Fiat', 'Coupe');
INSERT INTO `Model` VALUES ('Fiat', 'Croma');
INSERT INTO `Model` VALUES ('Fiat', 'Doblo');
INSERT INTO `Model` VALUES ('Fiat', 'Duna');
INSERT INTO `Model` VALUES ('Fiat', 'Fiorino');
INSERT INTO `Model` VALUES ('Fiat', 'Freemont');
INSERT INTO `Model` VALUES ('Fiat', 'Fullback');
INSERT INTO `Model` VALUES ('Fiat', 'Idea');
INSERT INTO `Model` VALUES ('Fiat', 'Linea');
INSERT INTO `Model` VALUES ('Fiat', 'Marea');
INSERT INTO `Model` VALUES ('Fiat', 'Multipla');
INSERT INTO `Model` VALUES ('Fiat', 'Palio');
INSERT INTO `Model` VALUES ('Fiat', 'Panda');
INSERT INTO `Model` VALUES ('Fiat', 'Punto');
INSERT INTO `Model` VALUES ('Fiat', 'Qubo');
INSERT INTO `Model` VALUES ('Fiat', 'Regata');
INSERT INTO `Model` VALUES ('Fiat', 'Ritmo');
INSERT INTO `Model` VALUES ('Fiat', 'Scudo');
INSERT INTO `Model` VALUES ('Fiat', 'Sedici');
INSERT INTO `Model` VALUES ('Fiat', 'Seicento');
INSERT INTO `Model` VALUES ('Fiat', 'Siena');
INSERT INTO `Model` VALUES ('Fiat', 'Stilo');
INSERT INTO `Model` VALUES ('Fiat', 'Strada');
INSERT INTO `Model` VALUES ('Fiat', 'Tempra');
INSERT INTO `Model` VALUES ('Fiat', 'Tipo');
INSERT INTO `Model` VALUES ('Fiat', 'Ulysse');
INSERT INTO `Model` VALUES ('Fiat', 'Uno');
INSERT INTO `Model` VALUES ('Fiat', 'X 1/9');
INSERT INTO `Model` VALUES ('Ford', 'Aerostar');
INSERT INTO `Model` VALUES ('Ford', 'Aspire');
INSERT INTO `Model` VALUES ('Ford', 'B-MAX');
INSERT INTO `Model` VALUES ('Ford', 'Bronco');
INSERT INTO `Model` VALUES ('Ford', 'Bronco Sport');
INSERT INTO `Model` VALUES ('Ford', 'Bronco-II');
INSERT INTO `Model` VALUES ('Ford', 'C-MAX');
INSERT INTO `Model` VALUES ('Ford', 'Capri');
INSERT INTO `Model` VALUES ('Ford', 'Consul');
INSERT INTO `Model` VALUES ('Ford', 'Contour');
INSERT INTO `Model` VALUES ('Ford', 'Cortina');
INSERT INTO `Model` VALUES ('Ford', 'Cougar');
INSERT INTO `Model` VALUES ('Ford', 'Country Squire');
INSERT INTO `Model` VALUES ('Ford', 'Crown Victoria');
INSERT INTO `Model` VALUES ('Ford', 'Custom');
INSERT INTO `Model` VALUES ('Ford', 'Econoline');
INSERT INTO `Model` VALUES ('Ford', 'Econovan');
INSERT INTO `Model` VALUES ('Ford', 'EcoSport');
INSERT INTO `Model` VALUES ('Ford', 'Edge');
INSERT INTO `Model` VALUES ('Ford', 'Escape');
INSERT INTO `Model` VALUES ('Ford', 'Escort');
INSERT INTO `Model` VALUES ('Ford', 'Escort (North America)');
INSERT INTO `Model` VALUES ('Ford', 'Everest');
INSERT INTO `Model` VALUES ('Ford', 'Excursion');
INSERT INTO `Model` VALUES ('Ford', 'Expedition');
INSERT INTO `Model` VALUES ('Ford', 'Explorer');
INSERT INTO `Model` VALUES ('Ford', 'Explorer Sport Trac');
INSERT INTO `Model` VALUES ('Ford', 'F-150');
INSERT INTO `Model` VALUES ('Ford', 'F-2');
INSERT INTO `Model` VALUES ('Ford', 'Fairlane');
INSERT INTO `Model` VALUES ('Ford', 'Fairmont');
INSERT INTO `Model` VALUES ('Ford', 'Falcon');
INSERT INTO `Model` VALUES ('Ford', 'Festiva');
INSERT INTO `Model` VALUES ('Ford', 'Fiesta');
INSERT INTO `Model` VALUES ('Ford', 'Fiesta ST');
INSERT INTO `Model` VALUES ('Ford', 'Five Hundred');
INSERT INTO `Model` VALUES ('Ford', 'Flex');
INSERT INTO `Model` VALUES ('Ford', 'Focus');
INSERT INTO `Model` VALUES ('Ford', 'Focus RS');
INSERT INTO `Model` VALUES ('Ford', 'Focus ST');
INSERT INTO `Model` VALUES ('Ford', 'Freda');
INSERT INTO `Model` VALUES ('Ford', 'Freestar');
INSERT INTO `Model` VALUES ('Ford', 'Freestyle');
INSERT INTO `Model` VALUES ('Ford', 'Fusion');
INSERT INTO `Model` VALUES ('Ford', 'Fusion (North America)');
INSERT INTO `Model` VALUES ('Ford', 'Galaxie');
INSERT INTO `Model` VALUES ('Ford', 'Galaxy');
INSERT INTO `Model` VALUES ('Ford', 'GPA');
INSERT INTO `Model` VALUES ('Ford', 'Granada');
INSERT INTO `Model` VALUES ('Ford', 'Granada (North America)');
INSERT INTO `Model` VALUES ('Ford', 'GT');
INSERT INTO `Model` VALUES ('Ford', 'GT40');
INSERT INTO `Model` VALUES ('Ford', 'Ikon');
INSERT INTO `Model` VALUES ('Ford', 'Ixion');
INSERT INTO `Model` VALUES ('Ford', 'KA');
INSERT INTO `Model` VALUES ('Ford', 'Kuga');
INSERT INTO `Model` VALUES ('Ford', 'Laser');
INSERT INTO `Model` VALUES ('Ford', 'LTD Country Squire');
INSERT INTO `Model` VALUES ('Ford', 'LTD Crown Victoria');
INSERT INTO `Model` VALUES ('Ford', 'M151');
INSERT INTO `Model` VALUES ('Ford', 'Mainline');
INSERT INTO `Model` VALUES ('Ford', 'Maverick');
INSERT INTO `Model` VALUES ('Ford', '`Model` A');
INSERT INTO `Model` VALUES ('Ford', '`Model` T');
INSERT INTO `Model` VALUES ('Ford', 'Mondeo');
INSERT INTO `Model` VALUES ('Ford', 'Mondeo ST');
INSERT INTO `Model` VALUES ('Ford', 'Mustang');
INSERT INTO `Model` VALUES ('Ford', 'Mustang Mach-E');
INSERT INTO `Model` VALUES ('Ford', 'Orion');
INSERT INTO `Model` VALUES ('Ford', 'Probe');
INSERT INTO `Model` VALUES ('Ford', 'Puma');
INSERT INTO `Model` VALUES ('Ford', 'Puma ST');
INSERT INTO `Model` VALUES ('Ford', 'Ranchero');
INSERT INTO `Model` VALUES ('Ford', 'Ranger');
INSERT INTO `Model` VALUES ('Ford', 'Ranger (North America)');
INSERT INTO `Model` VALUES ('Ford', 'S-MAX');
INSERT INTO `Model` VALUES ('Ford', 'Scorpio');
INSERT INTO `Model` VALUES ('Ford', 'Sierra');
INSERT INTO `Model` VALUES ('Ford', 'Spectron');
INSERT INTO `Model` VALUES ('Ford', 'Taunus');
INSERT INTO `Model` VALUES ('Ford', 'Taurus');
INSERT INTO `Model` VALUES ('Ford', 'Taurus X');
INSERT INTO `Model` VALUES ('Ford', 'Telstar');
INSERT INTO `Model` VALUES ('Ford', 'Tempo');
INSERT INTO `Model` VALUES ('Ford', 'Territory');
INSERT INTO `Model` VALUES ('Ford', 'Thunderbird');
INSERT INTO `Model` VALUES ('Ford', 'Torino');
INSERT INTO `Model` VALUES ('Ford', 'Tourneo Connect');
INSERT INTO `Model` VALUES ('Ford', 'Tourneo Courier');
INSERT INTO `Model` VALUES ('Ford', 'Tourneo Custom');
INSERT INTO `Model` VALUES ('Ford', 'Transit Connect');
INSERT INTO `Model` VALUES ('Ford', 'Transit Custom');
INSERT INTO `Model` VALUES ('Ford', 'V8');
INSERT INTO `Model` VALUES ('Ford', 'Windstar');
INSERT INTO `Model` VALUES ('Ford', 'Zephyr');
INSERT INTO `Model` VALUES ('Geely', 'Atlas');
INSERT INTO `Model` VALUES ('Geely', 'Atlas Pro');
INSERT INTO `Model` VALUES ('Geely', 'Beauty Leopard');
INSERT INTO `Model` VALUES ('Geely', 'CK (Otaka)');
INSERT INTO `Model` VALUES ('Geely', 'Coolray');
INSERT INTO `Model` VALUES ('Geely', 'Emgrand 7');
INSERT INTO `Model` VALUES ('Geely', 'Emgrand EC7');
INSERT INTO `Model` VALUES ('Geely', 'Emgrand EC8');
INSERT INTO `Model` VALUES ('Geely', 'Emgrand GT');
INSERT INTO `Model` VALUES ('Geely', 'Emgrand X7');
INSERT INTO `Model` VALUES ('Geely', 'FC (Vision)');
INSERT INTO `Model` VALUES ('Geely', 'GC6');
INSERT INTO `Model` VALUES ('Geely', 'GC9');
INSERT INTO `Model` VALUES ('Geely', 'Geometry A');
INSERT INTO `Model` VALUES ('Geely', 'Geometry C');
INSERT INTO `Model` VALUES ('Geely', 'GS');
INSERT INTO `Model` VALUES ('Geely', 'Haoqing');
INSERT INTO `Model` VALUES ('Geely', 'LC (Panda)');
INSERT INTO `Model` VALUES ('Geely', 'LC (Panda) Cross');
INSERT INTO `Model` VALUES ('Geely', 'MK');
INSERT INTO `Model` VALUES ('Geely', 'MK Cross');
INSERT INTO `Model` VALUES ('Geely', 'Monjaro');
INSERT INTO `Model` VALUES ('Geely', 'MR');
INSERT INTO `Model` VALUES ('Geely', 'Preface');
INSERT INTO `Model` VALUES ('Geely', 'SC7');
INSERT INTO `Model` VALUES ('Geely', 'Tugella');
INSERT INTO `Model` VALUES ('Geely', 'TX4');
INSERT INTO `Model` VALUES ('Great Wall', 'Coolbear');
INSERT INTO `Model` VALUES ('Great Wall', 'Cowry (V80)');
INSERT INTO `Model` VALUES ('Great Wall', 'Deer');
INSERT INTO `Model` VALUES ('Great Wall', 'Florid');
INSERT INTO `Model` VALUES ('Great Wall', 'Hover');
INSERT INTO `Model` VALUES ('Great Wall', 'Hover H3');
INSERT INTO `Model` VALUES ('Great Wall', 'Hover H5');
INSERT INTO `Model` VALUES ('Great Wall', 'Hover H6');
INSERT INTO `Model` VALUES ('Great Wall', 'Hover M1 (Peri 4x4)');
INSERT INTO `Model` VALUES ('Great Wall', 'Hover M2');
INSERT INTO `Model` VALUES ('Great Wall', 'Hover M4');
INSERT INTO `Model` VALUES ('Great Wall', 'Hover Pi');
INSERT INTO `Model` VALUES ('Great Wall', 'Pegasus');
INSERT INTO `Model` VALUES ('Great Wall', 'Peri');
INSERT INTO `Model` VALUES ('Great Wall', 'Poer');
INSERT INTO `Model` VALUES ('Great Wall', 'Safe');
INSERT INTO `Model` VALUES ('Great Wall', 'Sailor');
INSERT INTO `Model` VALUES ('Great Wall', 'Sing RUV');
INSERT INTO `Model` VALUES ('Great Wall', 'Socool');
INSERT INTO `Model` VALUES ('Great Wall', 'Voleex C10 (Phenom)');
INSERT INTO `Model` VALUES ('Great Wall', 'Voleex C30');
INSERT INTO `Model` VALUES ('Great Wall', 'Wingle');
INSERT INTO `Model` VALUES ('Great Wall', 'Wingle 7');
INSERT INTO `Model` VALUES ('Haima', '2');
INSERT INTO `Model` VALUES ('Haima', '3');
INSERT INTO `Model` VALUES ('Haima', '7');
INSERT INTO `Model` VALUES ('Haima', '8S');
INSERT INTO `Model` VALUES ('Haima', 'Family');
INSERT INTO `Model` VALUES ('Haima', 'Family F7');
INSERT INTO `Model` VALUES ('Haima', 'Freema');
INSERT INTO `Model` VALUES ('Haima', 'M3');
INSERT INTO `Model` VALUES ('Haima', 'S5');
INSERT INTO `Model` VALUES ('Honda', '145');
INSERT INTO `Model` VALUES ('Honda', 'Accord');
INSERT INTO `Model` VALUES ('Honda', 'Acty');
INSERT INTO `Model` VALUES ('Honda', 'Airwave');
INSERT INTO `Model` VALUES ('Honda', 'Ascot');
INSERT INTO `Model` VALUES ('Honda', 'Ascot Innova');
INSERT INTO `Model` VALUES ('Honda', 'Avancier');
INSERT INTO `Model` VALUES ('Honda', 'Ballade');
INSERT INTO `Model` VALUES ('Honda', 'Beat');
INSERT INTO `Model` VALUES ('Honda', 'Brio');
INSERT INTO `Model` VALUES ('Honda', 'Capa');
INSERT INTO `Model` VALUES ('Honda', 'City');
INSERT INTO `Model` VALUES ('Honda', 'Civic');
INSERT INTO `Model` VALUES ('Honda', 'Civic Ferio');
INSERT INTO `Model` VALUES ('Honda', 'Civic Type R');
INSERT INTO `Model` VALUES ('Honda', 'Clarity');
INSERT INTO `Model` VALUES ('Honda', 'Concerto');
INSERT INTO `Model` VALUES ('Honda', 'CR-V');
INSERT INTO `Model` VALUES ('Honda', 'CR-X');
INSERT INTO `Model` VALUES ('Honda', 'CR-Z');
INSERT INTO `Model` VALUES ('Honda', 'Crossroad');
INSERT INTO `Model` VALUES ('Honda', 'Crosstour');
INSERT INTO `Model` VALUES ('Honda', 'Domani');
INSERT INTO `Model` VALUES ('Honda', 'e');
INSERT INTO `Model` VALUES ('Honda', 'Edix');
INSERT INTO `Model` VALUES ('Honda', 'Element');
INSERT INTO `Model` VALUES ('Honda', 'Elysion');
INSERT INTO `Model` VALUES ('Honda', 'Fit');
INSERT INTO `Model` VALUES ('Honda', 'Fit Aria');
INSERT INTO `Model` VALUES ('Honda', 'Fit Shuttle');
INSERT INTO `Model` VALUES ('Honda', 'FR-V');
INSERT INTO `Model` VALUES ('Honda', 'Freed');
INSERT INTO `Model` VALUES ('Honda', 'Grace');
INSERT INTO `Model` VALUES ('Honda', 'Horizon');
INSERT INTO `Model` VALUES ('Honda', 'HR-V');
INSERT INTO `Model` VALUES ('Honda', 'Insight');
INSERT INTO `Model` VALUES ('Honda', 'Inspire');
INSERT INTO `Model` VALUES ('Honda', 'Integra');
INSERT INTO `Model` VALUES ('Honda', 'Integra SJ');
INSERT INTO `Model` VALUES ('Honda', 'Jade');
INSERT INTO `Model` VALUES ('Honda', 'Jazz');
INSERT INTO `Model` VALUES ('Honda', 'Lagreat');
INSERT INTO `Model` VALUES ('Honda', 'Legend');
INSERT INTO `Model` VALUES ('Honda', 'Life');
INSERT INTO `Model` VALUES ('Honda', 'Logo');
INSERT INTO `Model` VALUES ('Honda', 'MDX');
INSERT INTO `Model` VALUES ('Honda', 'Mobilio');
INSERT INTO `Model` VALUES ('Honda', 'Mobilio Spike');
INSERT INTO `Model` VALUES ('Honda', 'N-BOX');
INSERT INTO `Model` VALUES ('Honda', 'N-BOX Slash');
INSERT INTO `Model` VALUES ('Honda', 'N-One');
INSERT INTO `Model` VALUES ('Honda', 'N-WGN');
INSERT INTO `Model` VALUES ('Honda', 'N360');
INSERT INTO `Model` VALUES ('Honda', 'NSX');
INSERT INTO `Model` VALUES ('Honda', 'Odyssey');
INSERT INTO `Model` VALUES ('Honda', 'Odyssey (North America)');
INSERT INTO `Model` VALUES ('Honda', 'Orthia');
INSERT INTO `Model` VALUES ('Honda', 'Partner');
INSERT INTO `Model` VALUES ('Honda', 'Passport');
INSERT INTO `Model` VALUES ('Honda', 'Pilot');
INSERT INTO `Model` VALUES ('Honda', 'Prelude');
INSERT INTO `Model` VALUES ('Honda', 'Quint');
INSERT INTO `Model` VALUES ('Honda', 'Rafaga');
INSERT INTO `Model` VALUES ('Honda', 'Ridgeline');
INSERT INTO `Model` VALUES ('Honda', 'S-MX');
INSERT INTO `Model` VALUES ('Honda', 'S2000');
INSERT INTO `Model` VALUES ('Honda', 'S500');
INSERT INTO `Model` VALUES ('Honda', 'S600');
INSERT INTO `Model` VALUES ('Honda', 'S660');
INSERT INTO `Model` VALUES ('Honda', 'Saber');
INSERT INTO `Model` VALUES ('Honda', 'Shuttle');
INSERT INTO `Model` VALUES ('Honda', 'Stepwgn');
INSERT INTO `Model` VALUES ('Honda', 'Stream');
INSERT INTO `Model` VALUES ('Honda', 'Street');
INSERT INTO `Model` VALUES ('Honda', 'That`S');
INSERT INTO `Model` VALUES ('Honda', 'Today');
INSERT INTO `Model` VALUES ('Honda', 'Torneo');
INSERT INTO `Model` VALUES ('Honda', 'Vamos');
INSERT INTO `Model` VALUES ('Honda', 'Vezel');
INSERT INTO `Model` VALUES ('Honda', 'Vigor');
INSERT INTO `Model` VALUES ('Honda', 'Z');
INSERT INTO `Model` VALUES ('Honda', 'Zest');
INSERT INTO `Model` VALUES ('Hyundai', 'Accent');
INSERT INTO `Model` VALUES ('Hyundai', 'Aslan');
INSERT INTO `Model` VALUES ('Hyundai', 'Atos');
INSERT INTO `Model` VALUES ('Hyundai', 'Avante');
INSERT INTO `Model` VALUES ('Hyundai', 'Avante N');
INSERT INTO `Model` VALUES ('Hyundai', 'Azera');
INSERT INTO `Model` VALUES ('Hyundai', 'Bayon');
INSERT INTO `Model` VALUES ('Hyundai', 'Centennial');
INSERT INTO `Model` VALUES ('Hyundai', 'Click');
INSERT INTO `Model` VALUES ('Hyundai', 'Coupe');
INSERT INTO `Model` VALUES ('Hyundai', 'Creta');
INSERT INTO `Model` VALUES ('Hyundai', 'Dynasty');
INSERT INTO `Model` VALUES ('Hyundai', 'Elantra');
INSERT INTO `Model` VALUES ('Hyundai', 'Elantra N');
INSERT INTO `Model` VALUES ('Hyundai', 'Encino');
INSERT INTO `Model` VALUES ('Hyundai', 'Entourage');
INSERT INTO `Model` VALUES ('Hyundai', 'EON');
INSERT INTO `Model` VALUES ('Hyundai', 'Equus');
INSERT INTO `Model` VALUES ('Hyundai', 'Excel');
INSERT INTO `Model` VALUES ('Hyundai', 'Galloper');
INSERT INTO `Model` VALUES ('Hyundai', 'Genesis');
INSERT INTO `Model` VALUES ('Hyundai', 'Genesis Coupe');
INSERT INTO `Model` VALUES ('Hyundai', 'Getz');
INSERT INTO `Model` VALUES ('Hyundai', 'Grace');
INSERT INTO `Model` VALUES ('Hyundai', 'Grand Starex');
INSERT INTO `Model` VALUES ('Hyundai', 'Grandeur');
INSERT INTO `Model` VALUES ('Hyundai', 'H-1');
INSERT INTO `Model` VALUES ('Hyundai', 'H200');
INSERT INTO `Model` VALUES ('Hyundai', 'HB20');
INSERT INTO `Model` VALUES ('Hyundai', 'i10');
INSERT INTO `Model` VALUES ('Hyundai', 'i20');
INSERT INTO `Model` VALUES ('Hyundai', 'i20 N');
INSERT INTO `Model` VALUES ('Hyundai', 'i30');
INSERT INTO `Model` VALUES ('Hyundai', 'i30 N');
INSERT INTO `Model` VALUES ('Hyundai', 'i40');
INSERT INTO `Model` VALUES ('Hyundai', 'IONIQ');
INSERT INTO `Model` VALUES ('Hyundai', 'IONIQ 5');
INSERT INTO `Model` VALUES ('Hyundai', 'ix20');
INSERT INTO `Model` VALUES ('Hyundai', 'ix35');
INSERT INTO `Model` VALUES ('Hyundai', 'ix55');
INSERT INTO `Model` VALUES ('Hyundai', 'Kona');
INSERT INTO `Model` VALUES ('Hyundai', 'Kona N');
INSERT INTO `Model` VALUES ('Hyundai', 'Lantra');
INSERT INTO `Model` VALUES ('Hyundai', 'Lavita');
INSERT INTO `Model` VALUES ('Hyundai', 'Marcia');
INSERT INTO `Model` VALUES ('Hyundai', 'Matrix');
INSERT INTO `Model` VALUES ('Hyundai', 'Maxcruz');
INSERT INTO `Model` VALUES ('Hyundai', 'Palisade');
INSERT INTO `Model` VALUES ('Hyundai', 'Pony');
INSERT INTO `Model` VALUES ('Hyundai', 'Santa Cruz');
INSERT INTO `Model` VALUES ('Hyundai', 'Santa Fe');
INSERT INTO `Model` VALUES ('Hyundai', 'Santamo');
INSERT INTO `Model` VALUES ('Hyundai', 'Scoupe');
INSERT INTO `Model` VALUES ('Hyundai', 'Solaris');
INSERT INTO `Model` VALUES ('Hyundai', 'Sonata');
INSERT INTO `Model` VALUES ('Hyundai', 'Starex');
INSERT INTO `Model` VALUES ('Hyundai', 'Staria');
INSERT INTO `Model` VALUES ('Hyundai', 'Stellar');
INSERT INTO `Model` VALUES ('Hyundai', 'Terracan');
INSERT INTO `Model` VALUES ('Hyundai', 'Tiburon');
INSERT INTO `Model` VALUES ('Hyundai', 'Trajet');
INSERT INTO `Model` VALUES ('Hyundai', 'Tucson');
INSERT INTO `Model` VALUES ('Hyundai', 'Tuscani');
INSERT INTO `Model` VALUES ('Hyundai', 'Veloster');
INSERT INTO `Model` VALUES ('Hyundai', 'Venue');
INSERT INTO `Model` VALUES ('Hyundai', 'Veracruz');
INSERT INTO `Model` VALUES ('Hyundai', 'Verna');
INSERT INTO `Model` VALUES ('Hyundai', 'XG');
INSERT INTO `Model` VALUES ('Infiniti', 'EX');
INSERT INTO `Model` VALUES ('Infiniti', 'FX');
INSERT INTO `Model` VALUES ('Infiniti', 'G');
INSERT INTO `Model` VALUES ('Infiniti', 'I');
INSERT INTO `Model` VALUES ('Infiniti', 'J');
INSERT INTO `Model` VALUES ('Infiniti', 'JX');
INSERT INTO `Model` VALUES ('Infiniti', 'M');
INSERT INTO `Model` VALUES ('Infiniti', 'Q');
INSERT INTO `Model` VALUES ('Infiniti', 'Q30');
INSERT INTO `Model` VALUES ('Infiniti', 'Q40');
INSERT INTO `Model` VALUES ('Infiniti', 'Q50');
INSERT INTO `Model` VALUES ('Infiniti', 'Q60');
INSERT INTO `Model` VALUES ('Infiniti', 'Q70');
INSERT INTO `Model` VALUES ('Infiniti', 'QX30');
INSERT INTO `Model` VALUES ('Infiniti', 'QX4');
INSERT INTO `Model` VALUES ('Infiniti', 'QX50');
INSERT INTO `Model` VALUES ('Infiniti', 'QX55');
INSERT INTO `Model` VALUES ('Infiniti', 'QX56');
INSERT INTO `Model` VALUES ('Infiniti', 'QX60');
INSERT INTO `Model` VALUES ('Infiniti', 'QX70');
INSERT INTO `Model` VALUES ('Infiniti', 'QX80');
INSERT INTO `Model` VALUES ('Jeep', 'Cherokee');
INSERT INTO `Model` VALUES ('Jeep', 'CJ');
INSERT INTO `Model` VALUES ('Jeep', 'Comanche');
INSERT INTO `Model` VALUES ('Jeep', 'Commander');
INSERT INTO `Model` VALUES ('Jeep', 'Compass');
INSERT INTO `Model` VALUES ('Jeep', 'Gladiator');
INSERT INTO `Model` VALUES ('Jeep', 'Grand Cherokee');
INSERT INTO `Model` VALUES ('Jeep', 'Liberty (North America)');
INSERT INTO `Model` VALUES ('Jeep', 'Liberty (Patriot)');
INSERT INTO `Model` VALUES ('Jeep', 'Renegade');
INSERT INTO `Model` VALUES ('Jeep', 'Wagoneer');
INSERT INTO `Model` VALUES ('Jeep', 'Wrangler');
INSERT INTO `Model` VALUES ('Land Rover', 'Defender');
INSERT INTO `Model` VALUES ('Land Rover', 'Discovery');
INSERT INTO `Model` VALUES ('Land Rover', 'Discovery Sport');
INSERT INTO `Model` VALUES ('Land Rover', 'Freelander');
INSERT INTO `Model` VALUES ('Land Rover', 'Range Rover');
INSERT INTO `Model` VALUES ('Land Rover', 'Range Rover Evoque');
INSERT INTO `Model` VALUES ('Land Rover', 'Range Rover Sport');
INSERT INTO `Model` VALUES ('Land Rover', 'Range Rover Velar');
INSERT INTO `Model` VALUES ('Land Rover', 'Series I');
INSERT INTO `Model` VALUES ('Land Rover', 'Series II');
INSERT INTO `Model` VALUES ('Land Rover', 'Series III');
INSERT INTO `Model` VALUES ('Lexus', 'CT');
INSERT INTO `Model` VALUES ('Lexus', 'ES');
INSERT INTO `Model` VALUES ('Lexus', 'GS');
INSERT INTO `Model` VALUES ('Lexus', 'GS F');
INSERT INTO `Model` VALUES ('Lexus', 'GX');
INSERT INTO `Model` VALUES ('Lexus', 'HS');
INSERT INTO `Model` VALUES ('Lexus', 'IS');
INSERT INTO `Model` VALUES ('Lexus', 'IS F');
INSERT INTO `Model` VALUES ('Lexus', 'LC');
INSERT INTO `Model` VALUES ('Lexus', 'LFA');
INSERT INTO `Model` VALUES ('Lexus', 'LM');
INSERT INTO `Model` VALUES ('Lexus', 'LS');
INSERT INTO `Model` VALUES ('Lexus', 'LX');
INSERT INTO `Model` VALUES ('Lexus', 'NX');
INSERT INTO `Model` VALUES ('Lexus', 'RC');
INSERT INTO `Model` VALUES ('Lexus', 'RC F');
INSERT INTO `Model` VALUES ('Lexus', 'RX');
INSERT INTO `Model` VALUES ('Lexus', 'RZ');
INSERT INTO `Model` VALUES ('Lexus', 'SC');
INSERT INTO `Model` VALUES ('Lexus', 'UX');
INSERT INTO `Model` VALUES ('Lifan', '650 EV');
INSERT INTO `Model` VALUES ('Lifan', 'Breez (520)');
INSERT INTO `Model` VALUES ('Lifan', 'Cebrium (720)');
INSERT INTO `Model` VALUES ('Lifan', 'Celliya (530)');
INSERT INTO `Model` VALUES ('Lifan', 'Murman (820)');
INSERT INTO `Model` VALUES ('Lifan', 'Myway');
INSERT INTO `Model` VALUES ('Lifan', 'Smily');
INSERT INTO `Model` VALUES ('Lifan', 'Solano');
INSERT INTO `Model` VALUES ('Lifan', 'X50');
INSERT INTO `Model` VALUES ('Lifan', 'X60');
INSERT INTO `Model` VALUES ('Lifan', 'X70');
INSERT INTO `Model` VALUES ('Mazda', '1000');
INSERT INTO `Model` VALUES ('Mazda', '121');
INSERT INTO `Model` VALUES ('Mazda', '1300');
INSERT INTO `Model` VALUES ('Mazda', '2');
INSERT INTO `Model` VALUES ('Mazda', '3');
INSERT INTO `Model` VALUES ('Mazda', '3 MPS');
INSERT INTO `Model` VALUES ('Mazda', '323');
INSERT INTO `Model` VALUES ('Mazda', '5');
INSERT INTO `Model` VALUES ('Mazda', '6');
INSERT INTO `Model` VALUES ('Mazda', '6 MPS');
INSERT INTO `Model` VALUES ('Mazda', '616');
INSERT INTO `Model` VALUES ('Mazda', '626');
INSERT INTO `Model` VALUES ('Mazda', '818');
INSERT INTO `Model` VALUES ('Mazda', '929');
INSERT INTO `Model` VALUES ('Mazda', 'Atenza');
INSERT INTO `Model` VALUES ('Mazda', 'Autozam AZ-3');
INSERT INTO `Model` VALUES ('Mazda', 'Autozam Clef');
INSERT INTO `Model` VALUES ('Mazda', 'Axela');
INSERT INTO `Model` VALUES ('Mazda', 'AZ-1');
INSERT INTO `Model` VALUES ('Mazda', 'AZ-Offroad');
INSERT INTO `Model` VALUES ('Mazda', 'AZ-Wagon');
INSERT INTO `Model` VALUES ('Mazda', 'B-series');
INSERT INTO `Model` VALUES ('Mazda', 'Biante');
INSERT INTO `Model` VALUES ('Mazda', 'Bongo');
INSERT INTO `Model` VALUES ('Mazda', 'Bongo Friendee');
INSERT INTO `Model` VALUES ('Mazda', 'BT-50');
INSERT INTO `Model` VALUES ('Mazda', 'Capella');
INSERT INTO `Model` VALUES ('Mazda', 'Carol');
INSERT INTO `Model` VALUES ('Mazda', 'Chantez');
INSERT INTO `Model` VALUES ('Mazda', 'Cosmo');
INSERT INTO `Model` VALUES ('Mazda', 'Cronos');
INSERT INTO `Model` VALUES ('Mazda', 'CX-3');
INSERT INTO `Model` VALUES ('Mazda', 'CX-30');
INSERT INTO `Model` VALUES ('Mazda', 'CX-4');
INSERT INTO `Model` VALUES ('Mazda', 'CX-5');
INSERT INTO `Model` VALUES ('Mazda', 'CX-7');
INSERT INTO `Model` VALUES ('Mazda', 'CX-8');
INSERT INTO `Model` VALUES ('Mazda', 'CX-9');
INSERT INTO `Model` VALUES ('Mazda', 'Demio');
INSERT INTO `Model` VALUES ('Mazda', 'Efini MS-6');
INSERT INTO `Model` VALUES ('Mazda', 'Efini MS-8');
INSERT INTO `Model` VALUES ('Mazda', 'Efini MS-9');
INSERT INTO `Model` VALUES ('Mazda', 'Etude');
INSERT INTO `Model` VALUES ('Mazda', 'Eunos 100');
INSERT INTO `Model` VALUES ('Mazda', 'Eunos 300');
INSERT INTO `Model` VALUES ('Mazda', 'Eunos 500');
INSERT INTO `Model` VALUES ('Mazda', 'Eunos 800');
INSERT INTO `Model` VALUES ('Mazda', 'Eunos Cosmo');
INSERT INTO `Model` VALUES ('Mazda', 'Familia');
INSERT INTO `Model` VALUES ('Mazda', 'Flair');
INSERT INTO `Model` VALUES ('Mazda', 'Flair Crossover');
INSERT INTO `Model` VALUES ('Mazda', 'Flair Wagon');
INSERT INTO `Model` VALUES ('Mazda', 'Lantis');
INSERT INTO `Model` VALUES ('Mazda', 'Laputa');
INSERT INTO `Model` VALUES ('Mazda', 'Luce');
INSERT INTO `Model` VALUES ('Mazda', 'Millenia');
INSERT INTO `Model` VALUES ('Mazda', 'MPV');
INSERT INTO `Model` VALUES ('Mazda', 'MX-3');
INSERT INTO `Model` VALUES ('Mazda', 'MX-30');
INSERT INTO `Model` VALUES ('Mazda', 'MX-5');
INSERT INTO `Model` VALUES ('Mazda', 'MX-6');
INSERT INTO `Model` VALUES ('Mazda', 'Navajo');
INSERT INTO `Model` VALUES ('Mazda', 'Persona');
INSERT INTO `Model` VALUES ('Mazda', 'Premacy');
INSERT INTO `Model` VALUES ('Mazda', 'Proceed');
INSERT INTO `Model` VALUES ('Mazda', 'Proceed Levante');
INSERT INTO `Model` VALUES ('Mazda', 'Proceed Marvie');
INSERT INTO `Model` VALUES ('Mazda', 'Protege');
INSERT INTO `Model` VALUES ('Mazda', 'R360');
INSERT INTO `Model` VALUES ('Mazda', 'Revue');
INSERT INTO `Model` VALUES ('Mazda', 'Roadster');
INSERT INTO `Model` VALUES ('Mazda', 'RX-7');
INSERT INTO `Model` VALUES ('Mazda', 'RX-8');
INSERT INTO `Model` VALUES ('Mazda', 'Scrum');
INSERT INTO `Model` VALUES ('Mazda', 'Sentia');
INSERT INTO `Model` VALUES ('Mazda', 'Spiano');
INSERT INTO `Model` VALUES ('Mazda', 'Tribute');
INSERT INTO `Model` VALUES ('Mazda', 'Verisa');
INSERT INTO `Model` VALUES ('Mazda', 'Xedos 6');
INSERT INTO `Model` VALUES ('Mazda', 'Xedos 9');
INSERT INTO `Model` VALUES ('Mercedes-Benz', '190 (W201)');
INSERT INTO `Model` VALUES ('Mercedes-Benz', '190 SL');
INSERT INTO `Model` VALUES ('Mercedes-Benz', '220 (W187)');
INSERT INTO `Model` VALUES ('Mercedes-Benz', 'A-Класс');
INSERT INTO `Model` VALUES ('Mercedes-Benz', 'A-Класс AMG');
INSERT INTO `Model` VALUES ('Mercedes-Benz', 'AMG GT');
INSERT INTO `Model` VALUES ('Mercedes-Benz', 'AMG ONE');
INSERT INTO `Model` VALUES ('Mercedes-Benz', 'B-Класс');
INSERT INTO `Model` VALUES ('Mercedes-Benz', 'C-Класс');
INSERT INTO `Model` VALUES ('Mercedes-Benz', 'C-Класс AMG');
INSERT INTO `Model` VALUES ('Mercedes-Benz', 'Citan');
INSERT INTO `Model` VALUES ('Mercedes-Benz', 'CL-Класс');
INSERT INTO `Model` VALUES ('Mercedes-Benz', 'CL-Класс AMG');
INSERT INTO `Model` VALUES ('Mercedes-Benz', 'CLA');
INSERT INTO `Model` VALUES ('Mercedes-Benz', 'CLA AMG');
INSERT INTO `Model` VALUES ('Mercedes-Benz', 'CLC-Класс');
INSERT INTO `Model` VALUES ('Mercedes-Benz', 'CLK AMG GTR');
INSERT INTO `Model` VALUES ('Mercedes-Benz', 'CLK-Класс');
INSERT INTO `Model` VALUES ('Mercedes-Benz', 'CLK-Класс AMG');
INSERT INTO `Model` VALUES ('Mercedes-Benz', 'CLS');
INSERT INTO `Model` VALUES ('Mercedes-Benz', 'CLS AMG');
INSERT INTO `Model` VALUES ('Mercedes-Benz', 'E-Класс');
INSERT INTO `Model` VALUES ('Mercedes-Benz', 'E-Класс AMG');
INSERT INTO `Model` VALUES ('Mercedes-Benz', 'EQA');
INSERT INTO `Model` VALUES ('Mercedes-Benz', 'EQB');
INSERT INTO `Model` VALUES ('Mercedes-Benz', 'EQC');
INSERT INTO `Model` VALUES ('Mercedes-Benz', 'EQE');
INSERT INTO `Model` VALUES ('Mercedes-Benz', 'EQE AMG');
INSERT INTO `Model` VALUES ('Mercedes-Benz', 'EQS');
INSERT INTO `Model` VALUES ('Mercedes-Benz', 'EQS AMG');
INSERT INTO `Model` VALUES ('Mercedes-Benz', 'EQS SUV');
INSERT INTO `Model` VALUES ('Mercedes-Benz', 'EQV');
INSERT INTO `Model` VALUES ('Mercedes-Benz', 'G-Класс');
INSERT INTO `Model` VALUES ('Mercedes-Benz', 'G-Класс AMG');
INSERT INTO `Model` VALUES ('Mercedes-Benz', 'G-Класс AMG 6x6');
INSERT INTO `Model` VALUES ('Mercedes-Benz', 'GL-Класс');
INSERT INTO `Model` VALUES ('Mercedes-Benz', 'GL-Класс AMG');
INSERT INTO `Model` VALUES ('Mercedes-Benz', 'GLA');
INSERT INTO `Model` VALUES ('Mercedes-Benz', 'GLA AMG');
INSERT INTO `Model` VALUES ('Mercedes-Benz', 'GLB');
INSERT INTO `Model` VALUES ('Mercedes-Benz', 'GLB AMG');
INSERT INTO `Model` VALUES ('Mercedes-Benz', 'GLC');
INSERT INTO `Model` VALUES ('Mercedes-Benz', 'GLC AMG');
INSERT INTO `Model` VALUES ('Mercedes-Benz', 'GLC Coupe');
INSERT INTO `Model` VALUES ('Mercedes-Benz', 'GLC Coupe AMG');
INSERT INTO `Model` VALUES ('Mercedes-Benz', 'GLE');
INSERT INTO `Model` VALUES ('Mercedes-Benz', 'GLE AMG');
INSERT INTO `Model` VALUES ('Mercedes-Benz', 'GLE Coupe');
INSERT INTO `Model` VALUES ('Mercedes-Benz', 'GLE Coupe AMG');
INSERT INTO `Model` VALUES ('Mercedes-Benz', 'GLK-Класс');
INSERT INTO `Model` VALUES ('Mercedes-Benz', 'GLS');
INSERT INTO `Model` VALUES ('Mercedes-Benz', 'GLS AMG');
INSERT INTO `Model` VALUES ('Mercedes-Benz', 'M-Класс');
INSERT INTO `Model` VALUES ('Mercedes-Benz', 'M-Класс AMG');
INSERT INTO `Model` VALUES ('Mercedes-Benz', 'Marco Polo');
INSERT INTO `Model` VALUES ('Mercedes-Benz', 'Maybach G 650 Landaulet');
INSERT INTO `Model` VALUES ('Mercedes-Benz', 'Maybach GLS');
INSERT INTO `Model` VALUES ('Mercedes-Benz', 'Maybach S-Класс');
INSERT INTO `Model` VALUES ('Mercedes-Benz', 'Metris');
INSERT INTO `Model` VALUES ('Mercedes-Benz', 'R-Класс');
INSERT INTO `Model` VALUES ('Mercedes-Benz', 'R-Класс AMG');
INSERT INTO `Model` VALUES ('Mercedes-Benz', 'S-Класс');
INSERT INTO `Model` VALUES ('Mercedes-Benz', 'S-Класс AMG');
INSERT INTO `Model` VALUES ('Mercedes-Benz', 'Simplex');
INSERT INTO `Model` VALUES ('Mercedes-Benz', 'SL-Класс');
INSERT INTO `Model` VALUES ('Mercedes-Benz', 'SL-Класс AMG');
INSERT INTO `Model` VALUES ('Mercedes-Benz', 'SLC');
INSERT INTO `Model` VALUES ('Mercedes-Benz', 'SLC AMG');
INSERT INTO `Model` VALUES ('Mercedes-Benz', 'SLK-Класс');
INSERT INTO `Model` VALUES ('Mercedes-Benz', 'SLK-Класс AMG');
INSERT INTO `Model` VALUES ('Mercedes-Benz', 'SLR McLaren');
INSERT INTO `Model` VALUES ('Mercedes-Benz', 'SLS AMG');
INSERT INTO `Model` VALUES ('Mercedes-Benz', 'T-Класс');
INSERT INTO `Model` VALUES ('Mercedes-Benz', 'V-Класс');
INSERT INTO `Model` VALUES ('Mercedes-Benz', 'Vaneo');
INSERT INTO `Model` VALUES ('Mercedes-Benz', 'Viano');
INSERT INTO `Model` VALUES ('Mercedes-Benz', 'Vito');
INSERT INTO `Model` VALUES ('Mercedes-Benz', 'W100');
INSERT INTO `Model` VALUES ('Mercedes-Benz', 'W105');
INSERT INTO `Model` VALUES ('Mercedes-Benz', 'W108');
INSERT INTO `Model` VALUES ('Mercedes-Benz', 'W110');
INSERT INTO `Model` VALUES ('Mercedes-Benz', 'W111');
INSERT INTO `Model` VALUES ('Mercedes-Benz', 'W114');
INSERT INTO `Model` VALUES ('Mercedes-Benz', 'W115');
INSERT INTO `Model` VALUES ('Mercedes-Benz', 'W120');
INSERT INTO `Model` VALUES ('Mercedes-Benz', 'W121');
INSERT INTO `Model` VALUES ('Mercedes-Benz', 'W123');
INSERT INTO `Model` VALUES ('Mercedes-Benz', 'W124');
INSERT INTO `Model` VALUES ('Mercedes-Benz', 'W128');
INSERT INTO `Model` VALUES ('Mercedes-Benz', 'W136');
INSERT INTO `Model` VALUES ('Mercedes-Benz', 'W138');
INSERT INTO `Model` VALUES ('Mercedes-Benz', 'W142');
INSERT INTO `Model` VALUES ('Mercedes-Benz', 'W186');
INSERT INTO `Model` VALUES ('Mercedes-Benz', 'W188');
INSERT INTO `Model` VALUES ('Mercedes-Benz', 'W189');
INSERT INTO `Model` VALUES ('Mercedes-Benz', 'W191');
INSERT INTO `Model` VALUES ('Mercedes-Benz', 'W21');
INSERT INTO `Model` VALUES ('Mercedes-Benz', 'W29');
INSERT INTO `Model` VALUES ('Mercedes-Benz', 'X-Класс');
INSERT INTO `Model` VALUES ('Mitsubishi', '3000 GT');
INSERT INTO `Model` VALUES ('Mitsubishi', '500');
INSERT INTO `Model` VALUES ('Mitsubishi', 'Airtrek');
INSERT INTO `Model` VALUES ('Mitsubishi', 'Aspire');
INSERT INTO `Model` VALUES ('Mitsubishi', 'ASX');
INSERT INTO `Model` VALUES ('Mitsubishi', 'Attrage');
INSERT INTO `Model` VALUES ('Mitsubishi', 'Bravo');
INSERT INTO `Model` VALUES ('Mitsubishi', 'Carisma');
INSERT INTO `Model` VALUES ('Mitsubishi', 'Celeste');
INSERT INTO `Model` VALUES ('Mitsubishi', 'Challenger');
INSERT INTO `Model` VALUES ('Mitsubishi', 'Chariot');
INSERT INTO `Model` VALUES ('Mitsubishi', 'Colt');
INSERT INTO `Model` VALUES ('Mitsubishi', 'Cordia');
INSERT INTO `Model` VALUES ('Mitsubishi', 'Debonair');
INSERT INTO `Model` VALUES ('Mitsubishi', 'Delica');
INSERT INTO `Model` VALUES ('Mitsubishi', 'Delica D:2');
INSERT INTO `Model` VALUES ('Mitsubishi', 'Delica D:3');
INSERT INTO `Model` VALUES ('Mitsubishi', 'Delica D:5');
INSERT INTO `Model` VALUES ('Mitsubishi', 'Diamante');
INSERT INTO `Model` VALUES ('Mitsubishi', 'Dignity');
INSERT INTO `Model` VALUES ('Mitsubishi', 'Dingo');
INSERT INTO `Model` VALUES ('Mitsubishi', 'Dion');
INSERT INTO `Model` VALUES ('Mitsubishi', 'Eclipse');
INSERT INTO `Model` VALUES ('Mitsubishi', 'Eclipse Cross');
INSERT INTO `Model` VALUES ('Mitsubishi', 'eK Active');
INSERT INTO `Model` VALUES ('Mitsubishi', 'eK Classic');
INSERT INTO `Model` VALUES ('Mitsubishi', 'eK Custom');
INSERT INTO `Model` VALUES ('Mitsubishi', 'eK Space');
INSERT INTO `Model` VALUES ('Mitsubishi', 'eK Sport');
INSERT INTO `Model` VALUES ('Mitsubishi', 'eK Wagon');
INSERT INTO `Model` VALUES ('Mitsubishi', 'Emeraude');
INSERT INTO `Model` VALUES ('Mitsubishi', 'Endeavor');
INSERT INTO `Model` VALUES ('Mitsubishi', 'Eterna');
INSERT INTO `Model` VALUES ('Mitsubishi', 'Freeca');
INSERT INTO `Model` VALUES ('Mitsubishi', 'FTO');
INSERT INTO `Model` VALUES ('Mitsubishi', 'Galant');
INSERT INTO `Model` VALUES ('Mitsubishi', 'Galant Fortis');
INSERT INTO `Model` VALUES ('Mitsubishi', 'Grandis');
INSERT INTO `Model` VALUES ('Mitsubishi', 'GTO');
INSERT INTO `Model` VALUES ('Mitsubishi', 'i');
INSERT INTO `Model` VALUES ('Mitsubishi', 'i-MiEV');
INSERT INTO `Model` VALUES ('Mitsubishi', 'Jeep J');
INSERT INTO `Model` VALUES ('Mitsubishi', 'L200');
INSERT INTO `Model` VALUES ('Mitsubishi', 'L300');
INSERT INTO `Model` VALUES ('Mitsubishi', 'L400');
INSERT INTO `Model` VALUES ('Mitsubishi', 'Lancer');
INSERT INTO `Model` VALUES ('Mitsubishi', 'Lancer Cargo');
INSERT INTO `Model` VALUES ('Mitsubishi', 'Lancer Evolution');
INSERT INTO `Model` VALUES ('Mitsubishi', 'Lancer Ralliart');
INSERT INTO `Model` VALUES ('Mitsubishi', 'Legnum');
INSERT INTO `Model` VALUES ('Mitsubishi', 'Libero');
INSERT INTO `Model` VALUES ('Mitsubishi', 'Minica');
INSERT INTO `Model` VALUES ('Mitsubishi', 'Minicab');
INSERT INTO `Model` VALUES ('Mitsubishi', 'Mirage');
INSERT INTO `Model` VALUES ('Mitsubishi', 'Montero');
INSERT INTO `Model` VALUES ('Mitsubishi', 'Montero Sport');
INSERT INTO `Model` VALUES ('Mitsubishi', 'Outlander');
INSERT INTO `Model` VALUES ('Mitsubishi', 'Outlander Sport');
INSERT INTO `Model` VALUES ('Mitsubishi', 'Pajero');
INSERT INTO `Model` VALUES ('Mitsubishi', 'Pajero iO');
INSERT INTO `Model` VALUES ('Mitsubishi', 'Pajero Junior');
INSERT INTO `Model` VALUES ('Mitsubishi', 'Pajero Mini');
INSERT INTO `Model` VALUES ('Mitsubishi', 'Pajero Pinin');
INSERT INTO `Model` VALUES ('Mitsubishi', 'Pajero Sport');
INSERT INTO `Model` VALUES ('Mitsubishi', 'Pistachio');
INSERT INTO `Model` VALUES ('Mitsubishi', 'Proudia');
INSERT INTO `Model` VALUES ('Mitsubishi', 'Raider');
INSERT INTO `Model` VALUES ('Mitsubishi', 'RVR');
INSERT INTO `Model` VALUES ('Mitsubishi', 'Sapporo');
INSERT INTO `Model` VALUES ('Mitsubishi', 'Savrin');
INSERT INTO `Model` VALUES ('Mitsubishi', 'Sigma');
INSERT INTO `Model` VALUES ('Mitsubishi', 'Space Gear');
INSERT INTO `Model` VALUES ('Mitsubishi', 'Space Runner');
INSERT INTO `Model` VALUES ('Mitsubishi', 'Space Star');
INSERT INTO `Model` VALUES ('Mitsubishi', 'Space Wagon');
INSERT INTO `Model` VALUES ('Mitsubishi', 'Starion');
INSERT INTO `Model` VALUES ('Mitsubishi', 'Strada');
INSERT INTO `Model` VALUES ('Mitsubishi', 'Toppo');
INSERT INTO `Model` VALUES ('Mitsubishi', 'Town Box');
INSERT INTO `Model` VALUES ('Mitsubishi', 'Tredia');
INSERT INTO `Model` VALUES ('Mitsubishi', 'Triton');
INSERT INTO `Model` VALUES ('Mitsubishi', 'Xpander');
INSERT INTO `Model` VALUES ('Nissan', '100NX');
INSERT INTO `Model` VALUES ('Nissan', '180SX');
INSERT INTO `Model` VALUES ('Nissan', '200SX');
INSERT INTO `Model` VALUES ('Nissan', '240SX');
INSERT INTO `Model` VALUES ('Nissan', '280ZX');
INSERT INTO `Model` VALUES ('Nissan', '300ZX');
INSERT INTO `Model` VALUES ('Nissan', '350Z');
INSERT INTO `Model` VALUES ('Nissan', '370Z');
INSERT INTO `Model` VALUES ('Nissan', 'AD');
INSERT INTO `Model` VALUES ('Nissan', 'Almera');
INSERT INTO `Model` VALUES ('Nissan', 'Almera Classic');
INSERT INTO `Model` VALUES ('Nissan', 'Almera Tino');
INSERT INTO `Model` VALUES ('Nissan', 'Altima');
INSERT INTO `Model` VALUES ('Nissan', 'Ariya');
INSERT INTO `Model` VALUES ('Nissan', 'Armada');
INSERT INTO `Model` VALUES ('Nissan', 'Auster');
INSERT INTO `Model` VALUES ('Nissan', 'Avenir');
INSERT INTO `Model` VALUES ('Nissan', 'Bassara');
INSERT INTO `Model` VALUES ('Nissan', 'BE-1');
INSERT INTO `Model` VALUES ('Nissan', 'Bluebird');
INSERT INTO `Model` VALUES ('Nissan', 'Bluebird Maxima');
INSERT INTO `Model` VALUES ('Nissan', 'Bluebird Sylphy');
INSERT INTO `Model` VALUES ('Nissan', 'Caravan');
INSERT INTO `Model` VALUES ('Nissan', 'Cedric');
INSERT INTO `Model` VALUES ('Nissan', 'Cefiro');
INSERT INTO `Model` VALUES ('Nissan', 'Cherry');
INSERT INTO `Model` VALUES ('Nissan', 'Cima');
INSERT INTO `Model` VALUES ('Nissan', 'Clipper Rio');
INSERT INTO `Model` VALUES ('Nissan', 'Crew');
INSERT INTO `Model` VALUES ('Nissan', 'Cube');
INSERT INTO `Model` VALUES ('Nissan', 'Datsun');
INSERT INTO `Model` VALUES ('Nissan', 'Dayz');
INSERT INTO `Model` VALUES ('Nissan', 'Dayz Roox');
INSERT INTO `Model` VALUES ('Nissan', 'Dualis');
INSERT INTO `Model` VALUES ('Nissan', 'Elgrand');
INSERT INTO `Model` VALUES ('Nissan', 'Exa');
INSERT INTO `Model` VALUES ('Nissan', 'Expert');
INSERT INTO `Model` VALUES ('Nissan', 'Fairlady Z');
INSERT INTO `Model` VALUES ('Nissan', 'Figaro');
INSERT INTO `Model` VALUES ('Nissan', 'Fuga');
INSERT INTO `Model` VALUES ('Nissan', 'Gloria');
INSERT INTO `Model` VALUES ('Nissan', 'GT-R');
INSERT INTO `Model` VALUES ('Nissan', 'Homy');
INSERT INTO `Model` VALUES ('Nissan', 'Hypermini');
INSERT INTO `Model` VALUES ('Nissan', 'Juke');
INSERT INTO `Model` VALUES ('Nissan', 'Juke Nismo');
INSERT INTO `Model` VALUES ('Nissan', 'Kicks');
INSERT INTO `Model` VALUES ('Nissan', 'Kix');
INSERT INTO `Model` VALUES ('Nissan', 'Lafesta');
INSERT INTO `Model` VALUES ('Nissan', 'Langley');
INSERT INTO `Model` VALUES ('Nissan', 'Largo');
INSERT INTO `Model` VALUES ('Nissan', 'Latio');
INSERT INTO `Model` VALUES ('Nissan', 'Laurel');
INSERT INTO `Model` VALUES ('Nissan', 'Leaf');
INSERT INTO `Model` VALUES ('Nissan', 'Leopard');
INSERT INTO `Model` VALUES ('Nissan', 'Liberta Villa');
INSERT INTO `Model` VALUES ('Nissan', 'Liberty');
INSERT INTO `Model` VALUES ('Nissan', 'Livina');
INSERT INTO `Model` VALUES ('Nissan', 'Lucino');
INSERT INTO `Model` VALUES ('Nissan', 'March');
INSERT INTO `Model` VALUES ('Nissan', 'Maxima');
INSERT INTO `Model` VALUES ('Nissan', 'Micra');
INSERT INTO `Model` VALUES ('Nissan', 'Mistral');
INSERT INTO `Model` VALUES ('Nissan', 'Moco');
INSERT INTO `Model` VALUES ('Nissan', 'Murano');
INSERT INTO `Model` VALUES ('Nissan', 'Navara (Frontier)');
INSERT INTO `Model` VALUES ('Nissan', 'Note');
INSERT INTO `Model` VALUES ('Nissan', 'NP300');
INSERT INTO `Model` VALUES ('Nissan', 'NV100 Clipper');
INSERT INTO `Model` VALUES ('Nissan', 'NV200');
INSERT INTO `Model` VALUES ('Nissan', 'NV300');
INSERT INTO `Model` VALUES ('Nissan', 'NV350 Caravan');
INSERT INTO `Model` VALUES ('Nissan', 'NX Coupe');
INSERT INTO `Model` VALUES ('Nissan', 'Otti');
INSERT INTO `Model` VALUES ('Nissan', 'Pao');
INSERT INTO `Model` VALUES ('Nissan', 'Pathfinder');
INSERT INTO `Model` VALUES ('Nissan', 'Patrol');
INSERT INTO `Model` VALUES ('Nissan', 'Pino');
INSERT INTO `Model` VALUES ('Nissan', 'Pixo');
INSERT INTO `Model` VALUES ('Nissan', 'Prairie');
INSERT INTO `Model` VALUES ('Nissan', 'Presage');
INSERT INTO `Model` VALUES ('Nissan', 'Presea');
INSERT INTO `Model` VALUES ('Nissan', 'President');
INSERT INTO `Model` VALUES ('Nissan', 'Primastar');
INSERT INTO `Model` VALUES ('Nissan', 'Primera');
INSERT INTO `Model` VALUES ('Nissan', 'Pulsar');
INSERT INTO `Model` VALUES ('Nissan', 'Qashqai');
INSERT INTO `Model` VALUES ('Nissan', 'Qashqai+2');
INSERT INTO `Model` VALUES ('Nissan', 'Quest');
INSERT INTO `Model` VALUES ('Nissan', 'R`nessa');
INSERT INTO `Model` VALUES ('Nissan', 'Rasheen');
INSERT INTO `Model` VALUES ('Nissan', 'Rogue');
INSERT INTO `Model` VALUES ('Nissan', 'Rogue Sport');
INSERT INTO `Model` VALUES ('Nissan', 'Roox');
INSERT INTO `Model` VALUES ('Nissan', 'Safari');
INSERT INTO `Model` VALUES ('Nissan', 'Sentra');
INSERT INTO `Model` VALUES ('Nissan', 'Serena');
INSERT INTO `Model` VALUES ('Nissan', 'Silvia');
INSERT INTO `Model` VALUES ('Nissan', 'Skyline');
INSERT INTO `Model` VALUES ('Nissan', 'Skyline Crossover');
INSERT INTO `Model` VALUES ('Nissan', 'Stagea');
INSERT INTO `Model` VALUES ('Nissan', 'Stanza');
INSERT INTO `Model` VALUES ('Nissan', 'Sunny');
INSERT INTO `Model` VALUES ('Nissan', 'Sylphy Zero Emission');
INSERT INTO `Model` VALUES ('Nissan', 'Teana');
INSERT INTO `Model` VALUES ('Nissan', 'Terra');
INSERT INTO `Model` VALUES ('Nissan', 'Terrano');
INSERT INTO `Model` VALUES ('Nissan', 'Terrano Regulus');
INSERT INTO `Model` VALUES ('Nissan', 'Tiida');
INSERT INTO `Model` VALUES ('Nissan', 'Tino');
INSERT INTO `Model` VALUES ('Nissan', 'Titan');
INSERT INTO `Model` VALUES ('Nissan', 'Urvan');
INSERT INTO `Model` VALUES ('Nissan', 'Vanette');
INSERT INTO `Model` VALUES ('Nissan', 'Versa');
INSERT INTO `Model` VALUES ('Nissan', 'Wingroad');
INSERT INTO `Model` VALUES ('Nissan', 'X-Terra');
INSERT INTO `Model` VALUES ('Nissan', 'X-Trail');
INSERT INTO `Model` VALUES ('Nissan', 'Xterra');
INSERT INTO `Model` VALUES ('Nissan', 'Z');
INSERT INTO `Model` VALUES ('Opel', 'Adam');
INSERT INTO `Model` VALUES ('Opel', 'Admiral');
INSERT INTO `Model` VALUES ('Opel', 'Agila');
INSERT INTO `Model` VALUES ('Opel', 'Ampera');
INSERT INTO `Model` VALUES ('Opel', 'Antara');
INSERT INTO `Model` VALUES ('Opel', 'Ascona');
INSERT INTO `Model` VALUES ('Opel', 'Astra');
INSERT INTO `Model` VALUES ('Opel', 'Astra OPC');
INSERT INTO `Model` VALUES ('Opel', 'Calibra');
INSERT INTO `Model` VALUES ('Opel', 'Campo');
INSERT INTO `Model` VALUES ('Opel', 'Cascada');
INSERT INTO `Model` VALUES ('Opel', 'Combo');
INSERT INTO `Model` VALUES ('Opel', 'Commodore');
INSERT INTO `Model` VALUES ('Opel', 'Corsa');
INSERT INTO `Model` VALUES ('Opel', 'Corsa OPC');
INSERT INTO `Model` VALUES ('Opel', 'Crossland X');
INSERT INTO `Model` VALUES ('Opel', 'Diplomat');
INSERT INTO `Model` VALUES ('Opel', 'Frontera');
INSERT INTO `Model` VALUES ('Opel', 'Grandland X');
INSERT INTO `Model` VALUES ('Opel', 'GT');
INSERT INTO `Model` VALUES ('Opel', 'Insignia');
INSERT INTO `Model` VALUES ('Opel', 'Insignia OPC');
INSERT INTO `Model` VALUES ('Opel', 'Kadett');
INSERT INTO `Model` VALUES ('Opel', 'Kapitan');
INSERT INTO `Model` VALUES ('Opel', 'Karl');
INSERT INTO `Model` VALUES ('Opel', 'Manta');
INSERT INTO `Model` VALUES ('Opel', 'Meriva');
INSERT INTO `Model` VALUES ('Opel', 'Meriva OPC');
INSERT INTO `Model` VALUES ('Opel', 'Mokka');
INSERT INTO `Model` VALUES ('Opel', 'Monterey');
INSERT INTO `Model` VALUES ('Opel', 'Monza');
INSERT INTO `Model` VALUES ('Opel', 'Olympia');
INSERT INTO `Model` VALUES ('Opel', 'Omega');
INSERT INTO `Model` VALUES ('Opel', 'P4');
INSERT INTO `Model` VALUES ('Opel', 'Rekord');
INSERT INTO `Model` VALUES ('Opel', 'Senator');
INSERT INTO `Model` VALUES ('Opel', 'Signum');
INSERT INTO `Model` VALUES ('Opel', 'Sintra');
INSERT INTO `Model` VALUES ('Opel', 'Speedster');
INSERT INTO `Model` VALUES ('Opel', 'Super Six');
INSERT INTO `Model` VALUES ('Opel', 'Tigra');
INSERT INTO `Model` VALUES ('Opel', 'Vectra');
INSERT INTO `Model` VALUES ('Opel', 'Vectra OPC');
INSERT INTO `Model` VALUES ('Opel', 'Vita');
INSERT INTO `Model` VALUES ('Opel', 'Vivaro');
INSERT INTO `Model` VALUES ('Opel', 'Zafira');
INSERT INTO `Model` VALUES ('Opel', 'Zafira Life');
INSERT INTO `Model` VALUES ('Opel', 'Zafira OPC');
INSERT INTO `Model` VALUES ('Peugeot', '1007');
INSERT INTO `Model` VALUES ('Peugeot', '104');
INSERT INTO `Model` VALUES ('Peugeot', '106');
INSERT INTO `Model` VALUES ('Peugeot', '107');
INSERT INTO `Model` VALUES ('Peugeot', '108');
INSERT INTO `Model` VALUES ('Peugeot', '2008');
INSERT INTO `Model` VALUES ('Peugeot', '201');
INSERT INTO `Model` VALUES ('Peugeot', '202');
INSERT INTO `Model` VALUES ('Peugeot', '203');
INSERT INTO `Model` VALUES ('Peugeot', '204');
INSERT INTO `Model` VALUES ('Peugeot', '205');
INSERT INTO `Model` VALUES ('Peugeot', '205 GTi');
INSERT INTO `Model` VALUES ('Peugeot', '206');
INSERT INTO `Model` VALUES ('Peugeot', '207');
INSERT INTO `Model` VALUES ('Peugeot', '208');
INSERT INTO `Model` VALUES ('Peugeot', '208 GTi');
INSERT INTO `Model` VALUES ('Peugeot', '3008');
INSERT INTO `Model` VALUES ('Peugeot', '301');
INSERT INTO `Model` VALUES ('Peugeot', '304');
INSERT INTO `Model` VALUES ('Peugeot', '305');
INSERT INTO `Model` VALUES ('Peugeot', '306');
INSERT INTO `Model` VALUES ('Peugeot', '307');
INSERT INTO `Model` VALUES ('Peugeot', '308');
INSERT INTO `Model` VALUES ('Peugeot', '308 GTi');
INSERT INTO `Model` VALUES ('Peugeot', '309');
INSERT INTO `Model` VALUES ('Peugeot', '4007');
INSERT INTO `Model` VALUES ('Peugeot', '4008');
INSERT INTO `Model` VALUES ('Peugeot', '402');
INSERT INTO `Model` VALUES ('Peugeot', '403');
INSERT INTO `Model` VALUES ('Peugeot', '404');
INSERT INTO `Model` VALUES ('Peugeot', '405');
INSERT INTO `Model` VALUES ('Peugeot', '406');
INSERT INTO `Model` VALUES ('Peugeot', '407');
INSERT INTO `Model` VALUES ('Peugeot', '408');
INSERT INTO `Model` VALUES ('Peugeot', '5008');
INSERT INTO `Model` VALUES ('Peugeot', '504');
INSERT INTO `Model` VALUES ('Peugeot', '505');
INSERT INTO `Model` VALUES ('Peugeot', '508');
INSERT INTO `Model` VALUES ('Peugeot', '604');
INSERT INTO `Model` VALUES ('Peugeot', '605');
INSERT INTO `Model` VALUES ('Peugeot', '607');
INSERT INTO `Model` VALUES ('Peugeot', '806');
INSERT INTO `Model` VALUES ('Peugeot', '807');
INSERT INTO `Model` VALUES ('Peugeot', 'Bipper');
INSERT INTO `Model` VALUES ('Peugeot', 'Expert');
INSERT INTO `Model` VALUES ('Peugeot', 'iOn');
INSERT INTO `Model` VALUES ('Peugeot', 'Partner');
INSERT INTO `Model` VALUES ('Peugeot', 'RCZ');
INSERT INTO `Model` VALUES ('Peugeot', 'Rifter');
INSERT INTO `Model` VALUES ('Peugeot', 'Traveller');
INSERT INTO `Model` VALUES ('Renault', '10');
INSERT INTO `Model` VALUES ('Renault', '11');
INSERT INTO `Model` VALUES ('Renault', '12');
INSERT INTO `Model` VALUES ('Renault', '14');
INSERT INTO `Model` VALUES ('Renault', '15');
INSERT INTO `Model` VALUES ('Renault', '16');
INSERT INTO `Model` VALUES ('Renault', '17');
INSERT INTO `Model` VALUES ('Renault', '18');
INSERT INTO `Model` VALUES ('Renault', '19');
INSERT INTO `Model` VALUES ('Renault', '20');
INSERT INTO `Model` VALUES ('Renault', '21');
INSERT INTO `Model` VALUES ('Renault', '25');
INSERT INTO `Model` VALUES ('Renault', '30');
INSERT INTO `Model` VALUES ('Renault', '4');
INSERT INTO `Model` VALUES ('Renault', '4CV');
INSERT INTO `Model` VALUES ('Renault', '5');
INSERT INTO `Model` VALUES ('Renault', '6');
INSERT INTO `Model` VALUES ('Renault', '8');
INSERT INTO `Model` VALUES ('Renault', '9');
INSERT INTO `Model` VALUES ('Renault', 'Alaskan');
INSERT INTO `Model` VALUES ('Renault', 'Arkana');
INSERT INTO `Model` VALUES ('Renault', 'Austral');
INSERT INTO `Model` VALUES ('Renault', 'Avantime');
INSERT INTO `Model` VALUES ('Renault', 'Captur');
INSERT INTO `Model` VALUES ('Renault', 'Caravelle');
INSERT INTO `Model` VALUES ('Renault', 'City K-ZE');
INSERT INTO `Model` VALUES ('Renault', 'Clio');
INSERT INTO `Model` VALUES ('Renault', 'Clio RS');
INSERT INTO `Model` VALUES ('Renault', 'Clio V6');
INSERT INTO `Model` VALUES ('Renault', 'Dauphine');
INSERT INTO `Model` VALUES ('Renault', 'Dokker');
INSERT INTO `Model` VALUES ('Renault', 'Duster');
INSERT INTO `Model` VALUES ('Renault', 'Espace');
INSERT INTO `Model` VALUES ('Renault', 'Floride');
INSERT INTO `Model` VALUES ('Renault', 'Fluence');
INSERT INTO `Model` VALUES ('Renault', 'Fregate');
INSERT INTO `Model` VALUES ('Renault', 'Fuego');
INSERT INTO `Model` VALUES ('Renault', 'Kadjar');
INSERT INTO `Model` VALUES ('Renault', 'Kangoo');
INSERT INTO `Model` VALUES ('Renault', 'Kaptur');
INSERT INTO `Model` VALUES ('Renault', 'Koleos');
INSERT INTO `Model` VALUES ('Renault', 'KWID');
INSERT INTO `Model` VALUES ('Renault', 'Laguna');
INSERT INTO `Model` VALUES ('Renault', 'Latitude');
INSERT INTO `Model` VALUES ('Renault', 'Lodgy');
INSERT INTO `Model` VALUES ('Renault', 'Logan');
INSERT INTO `Model` VALUES ('Renault', 'Megane');
INSERT INTO `Model` VALUES ('Renault', 'Megane E-Tech');
INSERT INTO `Model` VALUES ('Renault', 'Megane RS');
INSERT INTO `Model` VALUES ('Renault', 'Modus');
INSERT INTO `Model` VALUES ('Renault', 'Rodeo');
INSERT INTO `Model` VALUES ('Renault', 'Safrane');
INSERT INTO `Model` VALUES ('Renault', 'Sandero');
INSERT INTO `Model` VALUES ('Renault', 'Sandero RS');
INSERT INTO `Model` VALUES ('Renault', 'Scenic');
INSERT INTO `Model` VALUES ('Renault', 'Sport Spider');
INSERT INTO `Model` VALUES ('Renault', 'Symbol');
INSERT INTO `Model` VALUES ('Renault', 'Talisman');
INSERT INTO `Model` VALUES ('Renault', 'Trafic');
INSERT INTO `Model` VALUES ('Renault', 'Twingo');
INSERT INTO `Model` VALUES ('Renault', 'Twizy');
INSERT INTO `Model` VALUES ('Renault', 'Vel Satis');
INSERT INTO `Model` VALUES ('Renault', 'Vivastella');
INSERT INTO `Model` VALUES ('Renault', 'Wind');
INSERT INTO `Model` VALUES ('Renault', 'ZOE');
INSERT INTO `Model` VALUES ('Skoda', '100 Series');
INSERT INTO `Model` VALUES ('Skoda', '105, 120');
INSERT INTO `Model` VALUES ('Skoda', '1200');
INSERT INTO `Model` VALUES ('Skoda', 'Citigo');
INSERT INTO `Model` VALUES ('Skoda', 'Enyaq');
INSERT INTO `Model` VALUES ('Skoda', 'Enyaq Coupe');
INSERT INTO `Model` VALUES ('Skoda', 'Enyaq Coupe RS');
INSERT INTO `Model` VALUES ('Skoda', 'Fabia');
INSERT INTO `Model` VALUES ('Skoda', 'Fabia RS');
INSERT INTO `Model` VALUES ('Skoda', 'Favorit');
INSERT INTO `Model` VALUES ('Skoda', 'Felicia');
INSERT INTO `Model` VALUES ('Skoda', 'Forman');
INSERT INTO `Model` VALUES ('Skoda', 'Kamiq');
INSERT INTO `Model` VALUES ('Skoda', 'Karoq');
INSERT INTO `Model` VALUES ('Skoda', 'Kodiaq');
INSERT INTO `Model` VALUES ('Skoda', 'Kodiaq RS');
INSERT INTO `Model` VALUES ('Skoda', 'Octavia');
INSERT INTO `Model` VALUES ('Skoda', 'Octavia RS');
INSERT INTO `Model` VALUES ('Skoda', 'Popular');
INSERT INTO `Model` VALUES ('Skoda', 'Rapid');
INSERT INTO `Model` VALUES ('Skoda', 'Roomster');
INSERT INTO `Model` VALUES ('Skoda', 'Scala');
INSERT INTO `Model` VALUES ('Skoda', 'Superb');
INSERT INTO `Model` VALUES ('Skoda', 'Yeti');
INSERT INTO `Model` VALUES ('SsangYong', 'Actyon');
INSERT INTO `Model` VALUES ('SsangYong', 'Actyon Sports');
INSERT INTO `Model` VALUES ('SsangYong', 'Chairman');
INSERT INTO `Model` VALUES ('SsangYong', 'Istana');
INSERT INTO `Model` VALUES ('SsangYong', 'Kallista');
INSERT INTO `Model` VALUES ('SsangYong', 'Korando');
INSERT INTO `Model` VALUES ('SsangYong', 'Korando Family');
INSERT INTO `Model` VALUES ('SsangYong', 'Korando Sports');
INSERT INTO `Model` VALUES ('SsangYong', 'Korando Turismo');
INSERT INTO `Model` VALUES ('SsangYong', 'Kyron');
INSERT INTO `Model` VALUES ('SsangYong', 'Musso');
INSERT INTO `Model` VALUES ('SsangYong', 'Nomad');
INSERT INTO `Model` VALUES ('SsangYong', 'Rexton');
INSERT INTO `Model` VALUES ('SsangYong', 'Rexton Sports');
INSERT INTO `Model` VALUES ('SsangYong', 'Rodius');
INSERT INTO `Model` VALUES ('SsangYong', 'Stavic');
INSERT INTO `Model` VALUES ('SsangYong', 'Tivoli');
INSERT INTO `Model` VALUES ('SsangYong', 'XLV');
INSERT INTO `Model` VALUES ('Subaru', '1000');
INSERT INTO `Model` VALUES ('Subaru', '360');
INSERT INTO `Model` VALUES ('Subaru', 'Alcyone');
INSERT INTO `Model` VALUES ('Subaru', 'Ascent');
INSERT INTO `Model` VALUES ('Subaru', 'Baja');
INSERT INTO `Model` VALUES ('Subaru', 'Bighorn');
INSERT INTO `Model` VALUES ('Subaru', 'Bistro');
INSERT INTO `Model` VALUES ('Subaru', 'Brat');
INSERT INTO `Model` VALUES ('Subaru', 'BRZ');
INSERT INTO `Model` VALUES ('Subaru', 'Crosstrek');
INSERT INTO `Model` VALUES ('Subaru', 'Dex');
INSERT INTO `Model` VALUES ('Subaru', 'Dias Wagon');
INSERT INTO `Model` VALUES ('Subaru', 'Domingo');
INSERT INTO `Model` VALUES ('Subaru', 'Exiga');
INSERT INTO `Model` VALUES ('Subaru', 'Forester');
INSERT INTO `Model` VALUES ('Subaru', 'Impreza');
INSERT INTO `Model` VALUES ('Subaru', 'Impreza WRX');
INSERT INTO `Model` VALUES ('Subaru', 'Impreza WRX STi');
INSERT INTO `Model` VALUES ('Subaru', 'Justy');
INSERT INTO `Model` VALUES ('Subaru', 'Legacy');
INSERT INTO `Model` VALUES ('Subaru', 'Legacy Lancaster');
INSERT INTO `Model` VALUES ('Subaru', 'Leone');
INSERT INTO `Model` VALUES ('Subaru', 'Levorg');
INSERT INTO `Model` VALUES ('Subaru', 'Libero');
INSERT INTO `Model` VALUES ('Subaru', 'Lucra');
INSERT INTO `Model` VALUES ('Subaru', 'Outback');
INSERT INTO `Model` VALUES ('Subaru', 'Pleo');
INSERT INTO `Model` VALUES ('Subaru', 'Pleo Plus');
INSERT INTO `Model` VALUES ('Subaru', 'R1');
INSERT INTO `Model` VALUES ('Subaru', 'R2');
INSERT INTO `Model` VALUES ('Subaru', 'Rex');
INSERT INTO `Model` VALUES ('Subaru', 'Sambar');
INSERT INTO `Model` VALUES ('Subaru', 'Solterra');
INSERT INTO `Model` VALUES ('Subaru', 'Stella');
INSERT INTO `Model` VALUES ('Subaru', 'SVX');
INSERT INTO `Model` VALUES ('Subaru', 'Traviq');
INSERT INTO `Model` VALUES ('Subaru', 'Trezia');
INSERT INTO `Model` VALUES ('Subaru', 'Tribeca');
INSERT INTO `Model` VALUES ('Subaru', 'Vivio');
INSERT INTO `Model` VALUES ('Subaru', 'WRX');
INSERT INTO `Model` VALUES ('Subaru', 'WRX STi');
INSERT INTO `Model` VALUES ('Subaru', 'XT');
INSERT INTO `Model` VALUES ('Subaru', 'XV');
INSERT INTO `Model` VALUES ('Suzuki', 'Across');
INSERT INTO `Model` VALUES ('Suzuki', 'Aerio');
INSERT INTO `Model` VALUES ('Suzuki', 'Alto');
INSERT INTO `Model` VALUES ('Suzuki', 'Alto Lapin');
INSERT INTO `Model` VALUES ('Suzuki', 'APV');
INSERT INTO `Model` VALUES ('Suzuki', 'Baleno');
INSERT INTO `Model` VALUES ('Suzuki', 'Cappuccino');
INSERT INTO `Model` VALUES ('Suzuki', 'Cara');
INSERT INTO `Model` VALUES ('Suzuki', 'Carry');
INSERT INTO `Model` VALUES ('Suzuki', 'Celerio');
INSERT INTO `Model` VALUES ('Suzuki', 'Cervo');
INSERT INTO `Model` VALUES ('Suzuki', 'Ciaz');
INSERT INTO `Model` VALUES ('Suzuki', 'Cultus');
INSERT INTO `Model` VALUES ('Suzuki', 'DZire');
INSERT INTO `Model` VALUES ('Suzuki', 'Equator');
INSERT INTO `Model` VALUES ('Suzuki', 'Ertiga');
INSERT INTO `Model` VALUES ('Suzuki', 'Escudo');
INSERT INTO `Model` VALUES ('Suzuki', 'Esteem');
INSERT INTO `Model` VALUES ('Suzuki', 'Every');
INSERT INTO `Model` VALUES ('Suzuki', 'Forenza');
INSERT INTO `Model` VALUES ('Suzuki', 'Fronte');
INSERT INTO `Model` VALUES ('Suzuki', 'Grand Vitara');
INSERT INTO `Model` VALUES ('Suzuki', 'Hustler');
INSERT INTO `Model` VALUES ('Suzuki', 'Ignis');
INSERT INTO `Model` VALUES ('Suzuki', 'Jimny');
INSERT INTO `Model` VALUES ('Suzuki', 'Kei');
INSERT INTO `Model` VALUES ('Suzuki', 'Kizashi');
INSERT INTO `Model` VALUES ('Suzuki', 'Landy');
INSERT INTO `Model` VALUES ('Suzuki', 'Liana');
INSERT INTO `Model` VALUES ('Suzuki', 'MR Wagon');
INSERT INTO `Model` VALUES ('Suzuki', 'Palette');
INSERT INTO `Model` VALUES ('Suzuki', 'Reno');
INSERT INTO `Model` VALUES ('Suzuki', 'S-Presso');
INSERT INTO `Model` VALUES ('Suzuki', 'Samurai');
INSERT INTO `Model` VALUES ('Suzuki', 'Sidekick');
INSERT INTO `Model` VALUES ('Suzuki', 'Solio');
INSERT INTO `Model` VALUES ('Suzuki', 'Spacia');
INSERT INTO `Model` VALUES ('Suzuki', 'Splash');
INSERT INTO `Model` VALUES ('Suzuki', 'Swace');
INSERT INTO `Model` VALUES ('Suzuki', 'Swift');
INSERT INTO `Model` VALUES ('Suzuki', 'SX4');
INSERT INTO `Model` VALUES ('Suzuki', 'Twin');
INSERT INTO `Model` VALUES ('Suzuki', 'Verona');
INSERT INTO `Model` VALUES ('Suzuki', 'Vitara');
INSERT INTO `Model` VALUES ('Suzuki', 'Wagon R');
INSERT INTO `Model` VALUES ('Suzuki', 'Wagon R+');
INSERT INTO `Model` VALUES ('Suzuki', 'X-90');
INSERT INTO `Model` VALUES ('Suzuki', 'Xbee');
INSERT INTO `Model` VALUES ('Suzuki', 'XL7');
INSERT INTO `Model` VALUES ('Toyota', '2000GT');
INSERT INTO `Model` VALUES ('Toyota', '4Runner');
INSERT INTO `Model` VALUES ('Toyota', 'Allex');
INSERT INTO `Model` VALUES ('Toyota', 'Allion');
INSERT INTO `Model` VALUES ('Toyota', 'Alphard');
INSERT INTO `Model` VALUES ('Toyota', 'Altezza');
INSERT INTO `Model` VALUES ('Toyota', 'Aqua');
INSERT INTO `Model` VALUES ('Toyota', 'Aristo');
INSERT INTO `Model` VALUES ('Toyota', 'Aurion');
INSERT INTO `Model` VALUES ('Toyota', 'Auris');
INSERT INTO `Model` VALUES ('Toyota', 'Avalon');
INSERT INTO `Model` VALUES ('Toyota', 'Avanza');
INSERT INTO `Model` VALUES ('Toyota', 'Avensis');
INSERT INTO `Model` VALUES ('Toyota', 'Avensis Verso');
INSERT INTO `Model` VALUES ('Toyota', 'Aygo');
INSERT INTO `Model` VALUES ('Toyota', 'Aygo X');
INSERT INTO `Model` VALUES ('Toyota', 'bB');
INSERT INTO `Model` VALUES ('Toyota', 'Belta');
INSERT INTO `Model` VALUES ('Toyota', 'Blade');
INSERT INTO `Model` VALUES ('Toyota', 'Blizzard');
INSERT INTO `Model` VALUES ('Toyota', 'Brevis');
INSERT INTO `Model` VALUES ('Toyota', 'bZ4X');
INSERT INTO `Model` VALUES ('Toyota', 'C-HR');
INSERT INTO `Model` VALUES ('Toyota', 'Caldina');
INSERT INTO `Model` VALUES ('Toyota', 'Cami');
INSERT INTO `Model` VALUES ('Toyota', 'Camry');
INSERT INTO `Model` VALUES ('Toyota', 'Camry Solara');
INSERT INTO `Model` VALUES ('Toyota', 'Carina');
INSERT INTO `Model` VALUES ('Toyota', 'Carina E');
INSERT INTO `Model` VALUES ('Toyota', 'Carina ED');
INSERT INTO `Model` VALUES ('Toyota', 'Cavalier');
INSERT INTO `Model` VALUES ('Toyota', 'Celica');
INSERT INTO `Model` VALUES ('Toyota', 'Celsior');
INSERT INTO `Model` VALUES ('Toyota', 'Century');
INSERT INTO `Model` VALUES ('Toyota', 'Chaser');
INSERT INTO `Model` VALUES ('Toyota', 'Classic');
INSERT INTO `Model` VALUES ('Toyota', 'Comfort');
INSERT INTO `Model` VALUES ('Toyota', 'COMS');
INSERT INTO `Model` VALUES ('Toyota', 'Corolla');
INSERT INTO `Model` VALUES ('Toyota', 'Corolla Cross');
INSERT INTO `Model` VALUES ('Toyota', 'Corolla II');
INSERT INTO `Model` VALUES ('Toyota', 'Corolla Levin');
INSERT INTO `Model` VALUES ('Toyota', 'Corolla Rumion');
INSERT INTO `Model` VALUES ('Toyota', 'Corolla Spacio');
INSERT INTO `Model` VALUES ('Toyota', 'Corolla Verso');
INSERT INTO `Model` VALUES ('Toyota', 'Corona');
INSERT INTO `Model` VALUES ('Toyota', 'Corona EXiV');
INSERT INTO `Model` VALUES ('Toyota', 'Corsa');
INSERT INTO `Model` VALUES ('Toyota', 'Cressida');
INSERT INTO `Model` VALUES ('Toyota', 'Cresta');
INSERT INTO `Model` VALUES ('Toyota', 'Crown');
INSERT INTO `Model` VALUES ('Toyota', 'Crown Majesta');
INSERT INTO `Model` VALUES ('Toyota', 'Curren');
INSERT INTO `Model` VALUES ('Toyota', 'Cynos');
INSERT INTO `Model` VALUES ('Toyota', 'Duet');
INSERT INTO `Model` VALUES ('Toyota', 'Echo');
INSERT INTO `Model` VALUES ('Toyota', 'Esquire');
INSERT INTO `Model` VALUES ('Toyota', 'Estima');
INSERT INTO `Model` VALUES ('Toyota', 'Etios');
INSERT INTO `Model` VALUES ('Toyota', 'FJ Cruiser');
INSERT INTO `Model` VALUES ('Toyota', 'Fortuner');
INSERT INTO `Model` VALUES ('Toyota', 'FunCargo');
INSERT INTO `Model` VALUES ('Toyota', 'Gaia');
INSERT INTO `Model` VALUES ('Toyota', 'GR86');
INSERT INTO `Model` VALUES ('Toyota', 'Grand HiAce');
INSERT INTO `Model` VALUES ('Toyota', 'Granvia');
INSERT INTO `Model` VALUES ('Toyota', 'GT86');
INSERT INTO `Model` VALUES ('Toyota', 'Harrier');
INSERT INTO `Model` VALUES ('Toyota', 'HiAce');
INSERT INTO `Model` VALUES ('Toyota', 'Highlander');
INSERT INTO `Model` VALUES ('Toyota', 'Hilux');
INSERT INTO `Model` VALUES ('Toyota', 'Hilux Surf');
INSERT INTO `Model` VALUES ('Toyota', 'Innova');
INSERT INTO `Model` VALUES ('Toyota', 'Ipsum');
INSERT INTO `Model` VALUES ('Toyota', 'iQ');
INSERT INTO `Model` VALUES ('Toyota', 'ISis');
INSERT INTO `Model` VALUES ('Toyota', 'Ist');
INSERT INTO `Model` VALUES ('Toyota', 'Kluger');
INSERT INTO `Model` VALUES ('Toyota', 'Land Cruiser');
INSERT INTO `Model` VALUES ('Toyota', 'Land Cruiser Prado');
INSERT INTO `Model` VALUES ('Toyota', 'Lite Ace');
INSERT INTO `Model` VALUES ('Toyota', 'Mark II');
INSERT INTO `Model` VALUES ('Toyota', 'Mark X');
INSERT INTO `Model` VALUES ('Toyota', 'Mark X ZiO');
INSERT INTO `Model` VALUES ('Toyota', 'MasterAce Surf');
INSERT INTO `Model` VALUES ('Toyota', 'Matrix');
INSERT INTO `Model` VALUES ('Toyota', 'Mega Cruiser');
INSERT INTO `Model` VALUES ('Toyota', 'Mirai');
INSERT INTO `Model` VALUES ('Toyota', '`Model` F');
INSERT INTO `Model` VALUES ('Toyota', 'MR-S');
INSERT INTO `Model` VALUES ('Toyota', 'MR2');
INSERT INTO `Model` VALUES ('Toyota', 'Nadia');
INSERT INTO `Model` VALUES ('Toyota', 'Noah');
INSERT INTO `Model` VALUES ('Toyota', 'Opa');
INSERT INTO `Model` VALUES ('Toyota', 'Origin');
INSERT INTO `Model` VALUES ('Toyota', 'Paseo');
INSERT INTO `Model` VALUES ('Toyota', 'Passo');
INSERT INTO `Model` VALUES ('Toyota', 'Passo Sette');
INSERT INTO `Model` VALUES ('Toyota', 'Picnic');
INSERT INTO `Model` VALUES ('Toyota', 'Pixis Epoch');
INSERT INTO `Model` VALUES ('Toyota', 'Pixis Joy');
INSERT INTO `Model` VALUES ('Toyota', 'Pixis Mega');
INSERT INTO `Model` VALUES ('Toyota', 'Pixis Space');
INSERT INTO `Model` VALUES ('Toyota', 'Pixis Van');
INSERT INTO `Model` VALUES ('Toyota', 'Platz');
INSERT INTO `Model` VALUES ('Toyota', 'Porte');
INSERT INTO `Model` VALUES ('Toyota', 'Premio');
INSERT INTO `Model` VALUES ('Toyota', 'Previa');
INSERT INTO `Model` VALUES ('Toyota', 'Prius');
INSERT INTO `Model` VALUES ('Toyota', 'Prius Alpha');
INSERT INTO `Model` VALUES ('Toyota', 'Prius c');
INSERT INTO `Model` VALUES ('Toyota', 'Prius v (+)');
INSERT INTO `Model` VALUES ('Toyota', 'ProAce');
INSERT INTO `Model` VALUES ('Toyota', 'ProAce City');
INSERT INTO `Model` VALUES ('Toyota', 'Probox');
INSERT INTO `Model` VALUES ('Toyota', 'Progres');
INSERT INTO `Model` VALUES ('Toyota', 'Pronard');
INSERT INTO `Model` VALUES ('Toyota', 'Publica');
INSERT INTO `Model` VALUES ('Toyota', 'Ractis');
INSERT INTO `Model` VALUES ('Toyota', 'Raize');
INSERT INTO `Model` VALUES ('Toyota', 'Raum');
INSERT INTO `Model` VALUES ('Toyota', 'RAV4');
INSERT INTO `Model` VALUES ('Toyota', 'Regius');
INSERT INTO `Model` VALUES ('Toyota', 'RegiusAce');
INSERT INTO `Model` VALUES ('Toyota', 'Roomy');
INSERT INTO `Model` VALUES ('Toyota', 'Rush');
INSERT INTO `Model` VALUES ('Toyota', 'Sai');
INSERT INTO `Model` VALUES ('Toyota', 'Scepter');
INSERT INTO `Model` VALUES ('Toyota', 'Sequoia');
INSERT INTO `Model` VALUES ('Toyota', 'Sera');
INSERT INTO `Model` VALUES ('Toyota', 'Sienna');
INSERT INTO `Model` VALUES ('Toyota', 'Sienta');
INSERT INTO `Model` VALUES ('Toyota', 'Soarer');
INSERT INTO `Model` VALUES ('Toyota', 'Soluna');
INSERT INTO `Model` VALUES ('Toyota', 'Spade');
INSERT INTO `Model` VALUES ('Toyota', 'Sparky');
INSERT INTO `Model` VALUES ('Toyota', 'Sports 800');
INSERT INTO `Model` VALUES ('Toyota', 'Sprinter');
INSERT INTO `Model` VALUES ('Toyota', 'Sprinter Carib');
INSERT INTO `Model` VALUES ('Toyota', 'Sprinter Marino');
INSERT INTO `Model` VALUES ('Toyota', 'Sprinter Trueno');
INSERT INTO `Model` VALUES ('Toyota', 'Starlet');
INSERT INTO `Model` VALUES ('Toyota', 'Succeed');
INSERT INTO `Model` VALUES ('Toyota', 'Supra');
INSERT INTO `Model` VALUES ('Toyota', 'Tacoma');
INSERT INTO `Model` VALUES ('Toyota', 'Tank');
INSERT INTO `Model` VALUES ('Toyota', 'Tercel');
INSERT INTO `Model` VALUES ('Toyota', 'Touring HiAce');
INSERT INTO `Model` VALUES ('Toyota', 'Town Ace');
INSERT INTO `Model` VALUES ('Toyota', 'Tundra');
INSERT INTO `Model` VALUES ('Toyota', 'Urban Cruiser');
INSERT INTO `Model` VALUES ('Toyota', 'Vanguard');
INSERT INTO `Model` VALUES ('Toyota', 'Vellfire');
INSERT INTO `Model` VALUES ('Toyota', 'Venza');
INSERT INTO `Model` VALUES ('Toyota', 'Verossa');
INSERT INTO `Model` VALUES ('Toyota', 'Verso');
INSERT INTO `Model` VALUES ('Toyota', 'Verso-S');
INSERT INTO `Model` VALUES ('Toyota', 'Vios');
INSERT INTO `Model` VALUES ('Toyota', 'Vista');
INSERT INTO `Model` VALUES ('Toyota', 'Vitz');
INSERT INTO `Model` VALUES ('Toyota', 'Voltz');
INSERT INTO `Model` VALUES ('Toyota', 'Voxy');
INSERT INTO `Model` VALUES ('Toyota', 'WiLL');
INSERT INTO `Model` VALUES ('Toyota', 'WiLL Cypha');
INSERT INTO `Model` VALUES ('Toyota', 'Windom');
INSERT INTO `Model` VALUES ('Toyota', 'Wish');
INSERT INTO `Model` VALUES ('Toyota', 'Yaris');
INSERT INTO `Model` VALUES ('Toyota', 'Yaris Cross');
INSERT INTO `Model` VALUES ('Toyota', 'Yaris Verso');
INSERT INTO `Model` VALUES ('Volkswagen', '181');
INSERT INTO `Model` VALUES ('Volkswagen', 'Amarok');
INSERT INTO `Model` VALUES ('Volkswagen', 'Arteon');
INSERT INTO `Model` VALUES ('Volkswagen', 'Arteon R');
INSERT INTO `Model` VALUES ('Volkswagen', 'Atlas');
INSERT INTO `Model` VALUES ('Volkswagen', 'Atlas Cross Sport');
INSERT INTO `Model` VALUES ('Volkswagen', 'Beetle');
INSERT INTO `Model` VALUES ('Volkswagen', 'Bora');
INSERT INTO `Model` VALUES ('Volkswagen', 'Caddy');
INSERT INTO `Model` VALUES ('Volkswagen', 'California');
INSERT INTO `Model` VALUES ('Volkswagen', 'Caravelle');
INSERT INTO `Model` VALUES ('Volkswagen', 'Corrado');
INSERT INTO `Model` VALUES ('Volkswagen', 'Derby');
INSERT INTO `Model` VALUES ('Volkswagen', 'Eos');
INSERT INTO `Model` VALUES ('Volkswagen', 'EuroVan');
INSERT INTO `Model` VALUES ('Volkswagen', 'Fox');
INSERT INTO `Model` VALUES ('Volkswagen', 'Gol');
INSERT INTO `Model` VALUES ('Volkswagen', 'Golf');
INSERT INTO `Model` VALUES ('Volkswagen', 'Golf Country');
INSERT INTO `Model` VALUES ('Volkswagen', 'Golf GTI');
INSERT INTO `Model` VALUES ('Volkswagen', 'Golf Plus');
INSERT INTO `Model` VALUES ('Volkswagen', 'Golf R');
INSERT INTO `Model` VALUES ('Volkswagen', 'Golf R32');
INSERT INTO `Model` VALUES ('Volkswagen', 'Golf Sportsvan');
INSERT INTO `Model` VALUES ('Volkswagen', 'ID.3');
INSERT INTO `Model` VALUES ('Volkswagen', 'ID.4');
INSERT INTO `Model` VALUES ('Volkswagen', 'ID.5');
INSERT INTO `Model` VALUES ('Volkswagen', 'ID.6');
INSERT INTO `Model` VALUES ('Volkswagen', 'ID.Buzz');
INSERT INTO `Model` VALUES ('Volkswagen', 'Iltis');
INSERT INTO `Model` VALUES ('Volkswagen', 'Jetta');
INSERT INTO `Model` VALUES ('Volkswagen', 'K70');
INSERT INTO `Model` VALUES ('Volkswagen', 'Karmann-Ghia');
INSERT INTO `Model` VALUES ('Volkswagen', 'Lavida');
INSERT INTO `Model` VALUES ('Volkswagen', 'Lupo');
INSERT INTO `Model` VALUES ('Volkswagen', 'Lupo GTI');
INSERT INTO `Model` VALUES ('Volkswagen', 'Multivan');
INSERT INTO `Model` VALUES ('Volkswagen', 'Parati');
INSERT INTO `Model` VALUES ('Volkswagen', 'Passat');
INSERT INTO `Model` VALUES ('Volkswagen', 'Passat (North America)');
INSERT INTO `Model` VALUES ('Volkswagen', 'Passat CC');
INSERT INTO `Model` VALUES ('Volkswagen', 'Phaeton');
INSERT INTO `Model` VALUES ('Volkswagen', 'Pointer');
INSERT INTO `Model` VALUES ('Volkswagen', 'Polo');
INSERT INTO `Model` VALUES ('Volkswagen', 'Polo GTI');
INSERT INTO `Model` VALUES ('Volkswagen', 'Polo R WRC');
INSERT INTO `Model` VALUES ('Volkswagen', 'Quantum');
INSERT INTO `Model` VALUES ('Volkswagen', 'Routan');
INSERT INTO `Model` VALUES ('Volkswagen', 'Santana');
INSERT INTO `Model` VALUES ('Volkswagen', 'Scirocco');
INSERT INTO `Model` VALUES ('Volkswagen', 'Scirocco R');
INSERT INTO `Model` VALUES ('Volkswagen', 'Sharan');
INSERT INTO `Model` VALUES ('Volkswagen', 'SpaceFox');
INSERT INTO `Model` VALUES ('Volkswagen', 'T-Cross');
INSERT INTO `Model` VALUES ('Volkswagen', 'T-Roc');
INSERT INTO `Model` VALUES ('Volkswagen', 'T-Roc R');
INSERT INTO `Model` VALUES ('Volkswagen', 'Taigo');
INSERT INTO `Model` VALUES ('Volkswagen', 'Taos');
INSERT INTO `Model` VALUES ('Volkswagen', 'Taro');
INSERT INTO `Model` VALUES ('Volkswagen', 'Teramont');
INSERT INTO `Model` VALUES ('Volkswagen', 'Tharu');
INSERT INTO `Model` VALUES ('Volkswagen', 'Tiguan');
INSERT INTO `Model` VALUES ('Volkswagen', 'Tiguan R');
INSERT INTO `Model` VALUES ('Volkswagen', 'Touareg');
INSERT INTO `Model` VALUES ('Volkswagen', 'Touran');
INSERT INTO `Model` VALUES ('Volkswagen', 'Transporter');
INSERT INTO `Model` VALUES ('Volkswagen', 'Type 1');
INSERT INTO `Model` VALUES ('Volkswagen', 'Type 166');
INSERT INTO `Model` VALUES ('Volkswagen', 'Type 2');
INSERT INTO `Model` VALUES ('Volkswagen', 'Type 3');
INSERT INTO `Model` VALUES ('Volkswagen', 'Type 4');
INSERT INTO `Model` VALUES ('Volkswagen', 'Type 82');
INSERT INTO `Model` VALUES ('Volkswagen', 'up!');
INSERT INTO `Model` VALUES ('Volkswagen', 'Vento');
INSERT INTO `Model` VALUES ('Volkswagen', 'XL1');
INSERT INTO `Model` VALUES ('Volvo', '120 Series');
INSERT INTO `Model` VALUES ('Volvo', '140 Series');
INSERT INTO `Model` VALUES ('Volvo', '164');
INSERT INTO `Model` VALUES ('Volvo', '240 Series');
INSERT INTO `Model` VALUES ('Volvo', '260 Series');
INSERT INTO `Model` VALUES ('Volvo', '300 Series');
INSERT INTO `Model` VALUES ('Volvo', '440');
INSERT INTO `Model` VALUES ('Volvo', '460');
INSERT INTO `Model` VALUES ('Volvo', '480');
INSERT INTO `Model` VALUES ('Volvo', '66');
INSERT INTO `Model` VALUES ('Volvo', '740');
INSERT INTO `Model` VALUES ('Volvo', '760');
INSERT INTO `Model` VALUES ('Volvo', '780');
INSERT INTO `Model` VALUES ('Volvo', '850');
INSERT INTO `Model` VALUES ('Volvo', '940');
INSERT INTO `Model` VALUES ('Volvo', '960');
INSERT INTO `Model` VALUES ('Volvo', 'C30');
INSERT INTO `Model` VALUES ('Volvo', 'C40');
INSERT INTO `Model` VALUES ('Volvo', 'C70');
INSERT INTO `Model` VALUES ('Volvo', 'Laplander');
INSERT INTO `Model` VALUES ('Volvo', 'P1800');
INSERT INTO `Model` VALUES ('Volvo', 'P1900');
INSERT INTO `Model` VALUES ('Volvo', 'PV444');
INSERT INTO `Model` VALUES ('Volvo', 'PV544');
INSERT INTO `Model` VALUES ('Volvo', 'S40');
INSERT INTO `Model` VALUES ('Volvo', 'S60');
INSERT INTO `Model` VALUES ('Volvo', 'S60 Cross Country');
INSERT INTO `Model` VALUES ('Volvo', 'S70');
INSERT INTO `Model` VALUES ('Volvo', 'S80');
INSERT INTO `Model` VALUES ('Volvo', 'S90');
INSERT INTO `Model` VALUES ('Volvo', 'V40');
INSERT INTO `Model` VALUES ('Volvo', 'V40 Cross Country');
INSERT INTO `Model` VALUES ('Volvo', 'V50');
INSERT INTO `Model` VALUES ('Volvo', 'V60');
INSERT INTO `Model` VALUES ('Volvo', 'V60 Cross Country');
INSERT INTO `Model` VALUES ('Volvo', 'V70');
INSERT INTO `Model` VALUES ('Volvo', 'V90');
INSERT INTO `Model` VALUES ('Volvo', 'V90 Cross Country');
INSERT INTO `Model` VALUES ('Volvo', 'XC40');
INSERT INTO `Model` VALUES ('Volvo', 'XC60');
INSERT INTO `Model` VALUES ('Volvo', 'XC70');
INSERT INTO `Model` VALUES ('Volvo', 'XC90');
